### ISSUE TITLE
FixedHostPortGenericContainer spring integration testing

### ISSUE THREAD

**Issue by MenadKADDOUR** [testcontainers/testcontainers-java#1005]
Hi Guys,

I've somme issue with my spring integration testing using spring and FixedHostPortGenericContainer.
Actually I think that my application is loaded and trying to connect to databse before this one is up, cause I want to launch it in my test via FixedHostPortGenericContainer.

this is what my code looks like:

  @ClassRule
    public static FixedHostPortGenericContainer oracle = new FixedHostPortGenericContainer
            (myDockerImage).withFixedExposedPort(1521,1521)  ;

Sometimes my test is green, sometimes I've the error: java.sql.SQLException:
 Listener refused the connection with the following error:
ORA-12528, TNS:listener: all appropriate instances are blocking new connections.

I've tried the different waiting strategies, but i've always the same issue.

Thank you for your help!!!

**Comment by kiview** [comment]
So first of all I'd recommend to not use a fixed host port container, since this is considered an antipattern ;)

The waiting strategy will not block the bootstrapping of the Spring context and there the error is probably occurring.

When integration testing a Spring context, you have to take care about dynamically injecting the mapped container ports into the Spring context, before it has initialized its `DataSource`s. There are a couple of different strategies for this, but in your case, I think it's easiest to use our special JDBC driver proxy:
https://www.testcontainers.org/usage/database_containers.html#jdbc-url

**Comment by topalavlad** [comment]
@kiview on the same note, what about anything that uses generic container? 
How would you overwrite `application.yml` properties?

**Comment by bsideup** [comment]
@topalavlad you may find this helpful:
https://github.com/testcontainers/testcontainers-java/tree/master/examples/spring-boot

**Comment by topalavlad** [comment]
@bsideup thanks, I thought about using system properties, but unfortunately this isn't a complete solution because I cannot run tests with different containers in parallel

**Comment by eddumelendez** [comment]
@topalavlad `DynamicPropertySource` was introduced in spring-framework 5.2.5 and suits very well for testcontainers and set the right properties coming from the container.

@MenadKADDOUR how can we help nowadays? or can we close the issue?

**Comment by kiview** [comment]
Closing, since all modern frameworks nowadays provide excellent support for using dynamic ports.
