### ISSUE TITLE
Question for users: what are you using testcontainers for?

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#116]
I'm just curious as to what people are using testcontainers for. I tried to keep the library quite broad in capability, but I suspect there are use cases I didn't explicitly plan for. I'd be really keen to understand how you're using it, or plan to use it!
- What kind of thing are you testing with it (e.g. webapps, some other kind of server, non-server tools)?
- Are you using it to provide test tools (e.g. selenium), provide dockerized dependencies for integration tests (such as DBs, other systems), or to run the system-under-test inside a container itself?
- Which modules, or just core GenericContainers?

**Comment by bsideup** [comment]
@rnorth,

We're testing our Java Agents by starting container with different Java applications + some satellites like different databases (actually, a lot of them, starting from Redis and up to Oracle DB), so it's more like "system-under-test" scenario.

Just core GenericContainer ATM, with some wrappers on top of it (i.e. GroovyContainer)

**Comment by bsideup** [comment]
We've had our own testing engine based on Docker internally in ZeroTurnaround, but once test containers project became popular we decided to throw it away and just backport differences because they were pretty similar, plus we love opensource :)

**Comment by rnorth** [comment]
@bsideup cool -thanks! I'm very happy that ZeroTurnaround are both using this and involved :smile:

**Comment by bsideup** [comment]
OpenSource FTW! :) We were happy to find that TestContainers is able to provide nearly everything we need for testing :)

**Comment by kaiwinter** [comment]
I'm using `oracle-xe` and `mysql` to test the persistence layers of two Java EE applications. The `ContainerDatabaseDriver` makes Hibernate to implicitly start a Docker container when an `EntityManager` gets created.

Currently I'm using the `GenericContainer` to start a custom container with Wildfly 10 and MariaDB. Arquillian then deploys our complete application to Wildfly and runs the integration tests.

**Comment by sskorol** [comment]
I'm not using it yet, but planning for raising Selenium infrustructure for running tests on. Will postpone it at least until scaling feature for `docker-compose` is implemented.

**Comment by rnorth** [comment]
For completeness, my own use of Testcontainers has mainly been for selenium functional testing of an AngularJS web application. We didn't want to maintain a chromedriver/firefox + xvfb/vnc environment on CI, but HTMLUnit and PhantomJS couldn't provide a good enough approximation, and was hard to debug when things went wrong. I wanted a tool that would eliminate some of the most common selenium headaches once and for all, and testcontainers was born.

Additionally I've used the generic containers support (in a slightly adapted form) for essentially doing iterative refactoring on an enormous pile of Oracle 12c schema migration scripts.

We'll be using this for API integration testing too, shortly, for which we'll probably use the docker compose and/or generic container support.

**Comment by monowai** [comment]
Hi @rnorth  - My UC, integration-testing, is all I'm using it for at the moment. I'm working backend to frontend so nice to know you're been there! 

The legacy config for my project was Spring/XML/Tomcat. Integration tests were using the poorly maintained tomcat7-maven-plugin. My stack: ElasticSearch, Neo4j, RabbitMQ, Riak, Redis and the integration services between them that we call FlockData. 

To make life easier, we reworked deployment to be via Docker and moved configuration to SpringBoot using JavaConfig. The move to SB cobbled the old school integration test - starting SB services is harder than you'd think using Maven.

My containers are built via the Spotify plugin and I had a number of compose scripts to start the stack in various configurations. Given that I could start the stack with Compose is seemed logical to find a way to use the same approach for integration testing - took a while for that penny to drop. 

This is where I came across `trestcontainers`. This project gives me a nice lightweight integration in to the docker environment using compose configurations and is thus far proving a great way to test services for integration purposes.

**Comment by HenrikSkriver** [comment]
Hi @rnorth

I am currently working on a project made up of Dockerized Spring Boot services using such components as MariaDB, MongoDB and RabbitMQ also running in containers.
Similar to @monowai we are using Spotify's docker maven plugin to produce container images for the Spring Boot services.
Each service also has a compose file which is used in mavens integration test phase to start the containers which the service under test directly interacts with - such as its database and RabbitMQ.

Having recently migrated to using Docker DNS removed the need for Docker links which made our Docker Compose files simpler as well as the Spring Boot services configuration.
So I set out to use the DockerComposeContainer in testcontainers 1.0.4 to get a closer integration between the tests and the containers. 
However, since the current solution relies on the Ambassador container which uses links to proxy the containers, it is not possible as far as I can see.

I made a new version of the dduportal-dockerfiles/docker-compose image which contains docker-compose 1.7 and then tried to build a local version of testcontainers that uses this image.
But the ambassador containers can not link to their target containers as expected.

I am looking very much forward to testcontainers supporting docker-compose version 2 format and relying on the DNS capabilities in Docker.
It should remove the need for the ambassador containers used as I see it and by using explicit container names it should also be possible to avoid these "identifier" strings used in the DockerComposeContainer.

Do you have any plans to update testcontainers to support docker-compose version 2 in the near future or what is you vision?

I really hope that testcontainers continues to develop as it provides a useful integration between docker containers and Java testing.
So thank you.

**Comment by rnorth** [comment]
I'm going to close this issue/question. It's been useful to get feedback, but we're now getting plenty of feedback through other channels 😄.
