### ISSUE TITLE
Could not get container for XXXXX in logs

### ISSUE THREAD

**Issue by monowai** [testcontainers/testcontainers-java#118]
Hi yah. I took a stab at this project today with great success - nice work! 

I'm deploying two of my own SpringBoot docker services via Compose but one of them is throwing the same exception 3 times during startup. Everything is deploying and working fine, so is there a trick to getting rid of this message? 

v 1.0.3

```
ERROR ${sys:PID} --- [pool-2-thread-1] 🐳 [richnorth/ambassador:latest]         : Could not start container
org.testcontainers.shaded.com.github.dockerjava.api.InternalServerErrorException: Could not get container for zecgqt_fdsearch_1
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.testcontainers.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)

```

**Comment by rnorth** [comment]
Thanks! :smile: 

Unfortunately there's no way to stop that failure from happening right now, though you could change logback filters to suppress the message for the appender named `🐳 [richnorth/ambassador:latest]`. Sorry that this is clunky at the moment.

This should clearly be improved, though, and the behaviour that's causing the message should be removed. As-is, the library attempts to start an 'ambassador container' (one that exposes ports that would otherwise only be accessible through container links) - but does so straight away after starting the docker compose container. Since the docker compose container takes some time to create the service containers defined in `docker-compose.yml`, the ambassador containers may fail to connect on the first few attempts.

I think I have a solution - I'll try this out and hopefully get a fix into the pipeline...

**Comment by monowai** [comment]
Cool - I just tested that against my stack and the fix looks good. Thanks!

**Comment by monowai** [comment]
This has started occurring again on `master` - at least on my 8gb Ubuntu build box running over at AWS. Is the wait time before panicking externally configurable?
