### ISSUE TITLE
Java Debug - Handshake failed

### ISSUE THREAD

**Issue by monowai** [testcontainers/testcontainers-java#122]
I'm trying to debug an integration issue in my Java stack. 

I've registered and exposed the debug port, but when I try and connect to from my IDE I get `handshake failed - connection prematurely closed`. The debugger is listening on `50900`. I guess this is an ambassador problem as when I run it via `docker run` debug works fine. Connecting to an illegal port states `connection refused`

Are there any config options around proxying? I'm thinking that when I get around to testing my service to service comms over HTTP (the issue I'm trying to debug) that they will fail to find each other on their defined linked service configuration. But I guess that's a second issue :) 

```
 new DockerComposeContainer(new File("src/test/resources/docker-compose.yml"))
                    .withExposedService("rabbit_1", 5672)
                    .withExposedService("fdengine_1", 8090)
                    .withExposedService("fdengine_1", 50900)
                    .withExposedService("fdsearch_1", 8091);

$ dps

CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
8e143ced1dbe        flockdata/fd-search           "java -jar /opt/flock"   8 minutes ago       Up 7 minutes        8081/tcp, 9201/tcp, 9301/tcp                          tbddtq_fdsearch_1
bf25816f9c9b        flockdata/fd-engine           "java -jar /opt/flock"   8 minutes ago       Up 7 minutes        7474/tcp, 8080/tcp, 50900/tcp                         tbddtq_fdengine_1
62442c970ac5        rabbitmq:3-management         "/docker-entrypoint.s"   8 minutes ago       Up 8 minutes        4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   tbddtq_rabbit_1
1e0dba8dd6cf        richnorth/ambassador:latest   "./ambassadorize"        8 minutes ago       Up 8 minutes        0.0.0.0:33196->5672/tcp                               tender_hopper
16ff57531cb3        richnorth/ambassador:latest   "./ambassadorize"        8 minutes ago       Up 8 minutes        0.0.0.0:33195->8090/tcp                               mad_stonebraker
c795a19c89a4        richnorth/ambassador:latest   "./ambassadorize"        8 minutes ago       Up 8 minutes        0.0.0.0:33194->8091/tcp                               desperate_hypatia
1bb21b567a82        richnorth/ambassador:latest   "./ambassadorize"        8 minutes ago       Up 8 minutes        0.0.0.0:33193->50900/tcp                              nauseous_kowalevski
```

**Comment by rnorth** [comment]
Hi Mike,
Sorry, that sounds odd - I'll have to try and reproduce. I've not tried an ambassador container with a Java debugger.. yet. Just to check:

- this is regular Java debugger JDWP - correct?
- could you provide the relevant bit of the server-side JVM config properties so that I can copy exactly? e.g. I'm guessing it's something like `-agentlib:jdwp=transport=dt_socket,server=y,address=50900,suspend=n`
- could you also provide the connection parameters you're using from the debugger side (e.g. IDE settings or transcript of using `jdb` to try and connect)?
- finally, are you using docker directly on a linux machine, or docker-machine on OS X, etc?

The ambassador container is a pretty basic HAProxy instance ([source](https://github.com/rnorth/ambassador)) which just sets up a TCP proxy for a single port. The container logs for the ambassador container _might_ reveal some useful information on the TCP session events.

The only thing that I can think of right now is that the `address` property in the JDWP settings _may_ need to match those that the client is using to connect. I vaguely recall seeing that in distant (pre-testcontainers) days. That's possibly not the cause though, so if not this will take a bit more digging...

Richard

**Comment by monowai** [comment]
Groan! Command args being passed via docker were not in the correct order (despite working when executed from the a $prompt). 

Thanks for looking over my shoulder. FWIW, this works
```
CMD ["java",\
     "-Xdebug","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=50900",\
     "-jar",\
     "/opt/flockdata/engine.jar",\
     "${JAVA_OPTS}"]
```

**Comment by monowai** [comment]
PBKAC

**Comment by Sergey80** [comment]
i use
 ENTRYPOINT ["java", "-Xdebug", "-Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=50900", "-Djava.security.egd=file:/dev/./urandom", "-jar","/app.jar", "${JAVA_OPTS}"]

and have the same problem..

**Comment by Sergey80** [comment]
or: ENTRYPOINT ["java", "-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=50900", "-Djava.security.egd=file:/dev/./urandom", "-jar","/app.jar", "${JAVA_OPTS}"]

**Comment by monowai** [comment]
I switched to using `docker-compose.yml` and use env vars instead. 
`_JAVA_OPTIONS: "-Xms256m -Xmx512m -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=61000"`

[My compose script ](https://github.com/monowai/flockdata.org/blob/master/fd-docker-staging/src/test/resources/docker-compose.yml)
