### ISSUE TITLE
Bind OracleContainer to a fixed port on the host machine

### ISSUE THREAD

**Issue by DynamicBit** [testcontainers/testcontainers-java#1358]
Hi,

how can I bind an OracleContainer to a fixed port on the host machine?

**Comment by kiview** [comment]
You can't and it's not advised. What's your use case, that depends on a fixed port?
Normally you should be able to use the `getJdbcUrl()` method to get the mapped port and inject it into your system under test.

In case you absolutely have to bind to a fixed port, you can always fall back to `FixedHostPortContainer`.

**Comment by DynamicBit** [comment]
Hi @kiview,

I have to test an application that interacts with a Oracle db. The port of this db is fixed and the application read them from a .properties-file.

**Comment by rnorth** [comment]
I think @bsideup's blog post probably sets out the best way to accomplish this: https://bsideup.github.io/posts/debugging_containers/

**Comment by bsideup** [comment]
@rnorth I would not recommend using it here, since it **should not** be used for the tests themselves, only for some debugging/introspection tools on the host machine. The users should continue using the random ports, and set them with, let's say, system properties like [here](https://github.com/testcontainers/testcontainers-java/blob/738c90a8f08b45ed7f7cb3bb49a9ad18cafacab5/examples/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java#L23) or framework's configuration mechanism
