### ISSUE TITLE
Testcontainers.exposeHostPorts not working when offline

### ISSUE THREAD

**Issue by vmassol** [testcontainers/testcontainers-java#1391]
The problem can be debugged in `RemoteDockerImage#resolve`.
The call to `List<Image> updatedImages = (List)listImagesCmd.exec()`  returns the sshd image but it has a null repoTags. Thus AVAILABLE_IMAGE_NAME_CACHE is not updated with it and it's pulled.

```$ docker inspect e716acb1cdb2
[
    {
        "Id": "sha256:e716acb1cdb228671503beae1f4048b711f7edcab5f1b0decaf7e380ce14e312",
        "RepoTags": [],
        "RepoDigests": [
            "quay.io/testcontainers/sshd@sha256:18aa929c653284189fc9cefa45b731021857b6047a0a1757e909f958f258f088"
        ],
..
```

@rnorth said: 
> Hmm, this could be a bug introduced during the refactoring of image identity handling (related to registry auth)

**Comment by vmassol** [comment]
I'm on TC 1.11.1.

**Comment by rnorth** [comment]
I've done some digging and put together a test that confirms this.

There are two problems:
1. As identified and solved by @bsideup, the default `TestcontainersConfiguration` for the sshd image uses a SHA256-versioned image rather than an image tag. This can be worked around via a properties file to override the default sshd image (see [docs](https://www.testcontainers.org/features/configuration/#customizing-images), although this option is not explicitly documented)
2. Testcontainers' image indexing code can't handle images that have SHA256 digests. We need a way to access the `RepoDigests` from docker-java's `Image` class. Unless I'm missing something, at the moment only `RepoTags` is mapped.

I'll raise a PR to fix issue (1), and a separate issue to track (2).

**Comment by rnorth** [comment]
Released in [1.11.2](https://github.com/testcontainers/testcontainers-java/releases/tag/1.11.2)!

**Comment by vmassol** [comment]
Thanks @rnorth , will try it later today :)

**Comment by vmassol** [comment]
Confirmed that it works! Thanks again
