### ISSUE TITLE
Being able to set the container name like docker --name

### ISSUE THREAD

**Issue by itudoben** [testcontainers/testcontainers-java#1430]
Hi, thx for such great framework. I just discovered it as I needed something like that.
I would like to be able to name the container other than the generated names docker does.
Right now I overrode it this way:
```
private static class MyGenericContainer<SELF extends MyGenericContainer<SELF>> extends GenericContainer<SELF> {
    MyGenericContainer(String dockerImageName, String containerName) {
      super(dockerImageName)
      this.containerName = containerName
    }

    @Override
    void close() {
      super.close()
    }
  }
```
Unfortunately it is set in at this line in GenericContainer.tryStart()
```
            containerName = containerInfo.getName();
```
Maybe there is a way to set it - in configure() but gets overriden still - and I have not found it.

Is there a way to do this? Is it something that can be added in future releases? 

Thx, long life to TC :)
JH

**Comment by itudoben** [comment]
Ok, I found the way to do this:
```
GenericContainer coordinatornew GenericContainer<>(DOCKER_IMAGE_NAME)
.withCreateContainerCmdModifier({ cmd -> cmd.withName('coordinator') })
```
This issue is now resolved, therefore closed.

**Comment by kiview** [comment]
HI @itudoben, nice that you found out this approach.

Just wondering, what is your use case for naming the container? Keep in mind, a static name can lead to possible conflicts when creating the container, making it problematic in shared environments and in case of paralellization.

**Comment by perlun** [comment]
> Just wondering, what is your use case for naming the container? Keep in mind, a static name can lead to possible conflicts when creating the container, making it problematic in shared environments and in case of paralellization.

A workaround for this is to add a random segment in your name, to have the best of both worlds: container names that more easily let you identify them, but still be reasonably unique. Something like this:

```java
public class RedisContainer extends GenericContainer<RedisContainer> {
    private static final Random RANDOM = new Random();

    public RedisContainer() {
        withCreateContainerCmdModifier( cmd -> cmd.withName( "redis-" + ( RANDOM.nextInt() & Integer.MAX_VALUE ) ) );
    }
}
```

**Comment by derlin** [comment]
***IMPORTANT*: this may break the reusability of containers**

If you want your containers to be reusable, using a random part in the name will make reusability fail. That is, the old containers will keep running, but new containers will be created. Why ? Because testcontainers uses the cmd as part of the comparison to detect if an existing container is already running and can be reused. Since you create a new name each time, the comparison will always fail.

This was a real disappointment, as I would love to have meaningful prefixes AND reusability. If someone has another idea to work around this limitation, I am all ears !

**Comment by kiview** [comment]
I would still like to know more about the use case behind identifying the containers per name when using Testcontainers. Could anyone elaborate on this?

**Comment by derlin** [comment]
@kiview In my organisation, we use testcontainers in integration tests. Most repositories need at least 4 different images / containers. Let's say I am working on two different repositories (working on tests, so having the reuse flag set to true), and also have a bunch of other containers running. Whenever I need to have a look at the logs of, say, kafka, I need to click on the details of each container in Docker desktop in order to find out which container is actually running kafka (and the right one). With Docker Desktop, even the image name doesn't render, due to the lack of space and the fact that our repository address is quite long, so we really have no choice but click on each.

If instead I were able to give meaningful names, I would have a list of containers like:
```
kafka-<random-uid>
keycloak-<random-uid>
minio-<random-uid>
...
```
Easy to see which is which (and then see the logs, delete, etc). 

Not all people in my organisation are well versed in using the terminal (or other tricks), and from Docker Desktop not having meaningful names makes everything harder. Does it make sense ?

**Comment by kiview** [comment]
I understand your explanation, but I would say for finding image-specific containers, using `docker ps` with [filters](https://docs.docker.com/engine/reference/commandline/ps/#filtering) should be a straightforward approach and I would recommend it over using the Docker Desktop GUI (and working around its display limitations) any time.

What is the use case for manually inspecting containers and logs? You can attach log consumers using Testcontainers and you can programmatically inspect containers using Testcontainers as well.

**Comment by astubbs** [comment]
In our case, it's when run on our build servers, and if containers are left running. The name can be used to identify which project is the culprit that left containers laying around. I.e. org with thousands or projects all running many containers each build.

**Comment by astubbs** [comment]
FYI, you can rename them after the fact using the docker client, along with their random name. Not sure how this way affects reuse.

`DockerClientFactory.lazyClient().renameContainerCmd(kafkaContainer.getContainerId()).withName(containerPrefix + containerName).exec();`

**Comment by lscoughlin** [comment]
Or, instead of injecting a random number, you could inject the build number/jobid, whatever. Now you're reusable in the build but not across builds, and you can identify it back.

**Comment by jakubkalicki** [comment]
> FYI, you can rename them after the fact using the docker client, along with their random name. Not sure how this way affects reuse.
> 
> `DockerClientFactory.lazyClient().renameContainerCmd(kafkaContainer.getContainerId()).withName(containerPrefix + containerName).exec();`

Unfortunately, this breaks reuse as well.

Any other workarounds? 🤔

**Comment by perlun** [comment]
> I would still like to know more about the use case behind identifying the containers per name when using Testcontainers. Could anyone elaborate on this?

Late to the party @kiview, but one use case I have is when running MariaDB via testcontainers. Sometimes you need to locally connect with the `mysql` CLI to run some queries towards the DB. Right now I have an alias (well, shell function) like this:

```bash
docker_mysql_port() {
    docker port $1 3306 | grep -v ::: | awk -F : '{ print $2 }'
}
```

I can then connect to the DB using a command like `mysql -P $(docker_mysql_port vibrant_germain) -utest -p test`. But the name `vibrant_germain` here is TBH quite useless; it's much more convenient (as @derlin noted) to have something like `mariadb-<random-uid>` in this case.

Yeah, you can probably run `docker ps` with an appropriate filter, but being able to just `docker ps` and quickly be able to scan the list of running containers seems useful, at least to me personally.

**Comment by eddumelendez** [comment]
Hi, have you tried [Testcontainers Desktop](https://testcontainers.com/desktop/)? You can go to `Services -> Open config location...` create a `mysql.toml` file with the following content:

```toml
ports = [
  {local-port = 3306, container-port = 3306},
]

selector.image-names = ["mysql"]
```

and you will be able to access the container using your local tools by using host 127.0.0.1 and port 3306

**Comment by perlun** [comment]
Thanks @eddumelendez, nice try. :slightly_smiling_face: However, I already have another MariaDB instance (it's actually MariaDB in my case rather than MySQL, despite my misleading shell function name :see_no_evil:) running which is exposed on `127.0.0.1:3306`. But I can of course just put the testcontainers instance on another port so that could still be useful.

As for Testcontainers Desktop in generla, thanks for letting me know about it, I haven't tried it. What are its licensing terms? Couldn't find any mention of the license on the web page nor by some quick googling.
