### ISSUE TITLE
Whitespaces are truncated from text values in init script in presence of C style comments

### ISSUE THREAD

**Issue by ParafeniukMikalaj** [testcontainers/testcontainers-java#1452]
Hi, I noticed, that test-containers removes whitespace characters from VARCHAR values in init script when C style comments are present.

Please check sample project demonstrating a problem: https://github.com/ParafeniukMikalaj/testcontainers-jdbc-test

**Comment by rnorth** [comment]
Not stale. Let’s check this again - if it’s not fixed in the latest improvements to ScriptUtils, we should add a test case and fix it.

**Comment by rnorth** [comment]
Sorry for leaving this so long @ParafeniukMikalaj. I've created a quick test case in #1702, which I believe is equivalent to your repro example and shows that the problem is no longer occurring. Please have a look if you have time.

Thank you for taking the time to report the issue and develop a repro example back in May; if this had still been a problem it would certainly have been important to fix, and having a test for this now lets us guard against regressions.
