### ISSUE TITLE
Expose port without mapping to host

### ISSUE THREAD

**Issue by pedro93** [testcontainers/testcontainers-java#1546]
Hello,

I'm having the following problem.
Setting up a FixedHostPortGenericContainer I want to expose a port without mapping it to the host so that using the container's Ip and known internal port I can communicate with it.

Is this possible? The most logical method `FixedHostPortGenericContainer.withExposedPorts`  will map the port to the host on some random port. This is not suitable to our use-case because the process running in the container needs to retrieve a final destination port through this channel (this is a Java RMI connection handshake process).

Thank you for the help and more so for developing this project!

**Comment by rnorth** [comment]
This is more of a question about Java RMI and Docker than Testcontainers specifically, but I'll try to help.

Firstly, have you also tried the `withFixedExposedPort` method on `FixedHostPortGenericContainer`? It sounds like you are looking for an exposed port that is consistent on both the test host and the container side. `FixedHostPortGenericContainer` is not something we like to recommend (due to risk of port clashes) but it's _one_ approach.

@bsideup's blog post [How to locally debug containers started by Testcontainers](https://bsideup.github.io/posts/debugging_containers/) is a more mature, nicer solution to the general problem than `FixedHostPortGenericContainer` - it may be worth a look.

These should be OK for the RMI registry; are you having problems with the client/server dynamic port binding? 

If so, another (non-Docker-specific) solution might help. There are various ways of making Java use a specific port for non-registry comms; [this way](https://stackoverflow.com/questions/43759967/java-rmi-server-in-docker-container/43772637#43772637) looks pretty interesting and was new to me! This would simplify the setup to just require port `1099` to be exposed - it depends how much control you have over your container's code, though.

**Comment by pedro93** [comment]
First of all, thank you very very much for taking the time to reply and help!

> Firstly, have you also tried the withFixedExposedPort method on FixedHostPortGenericContainer?
I have, while it works as you said it is not a recommended approach due to possible port clashes. This is a no go for us since we want to use test-containers in our CI, and need to run concurrent executions in the same worker. Port clashing prevents us from doing that.

The blog post link does not help with our case since we can connect to the RMI registry without issue, the problem is with the object port, which needs to know the IP of the container being launched.

As you mentioned I do not think this is a Test Containers issue but something else on my side, as such this issue can be closed.

Again thank you for taking the time.
