### ISSUE TITLE
Override localstack image using TestcontainersConfiguration

### ISSUE THREAD

**Issue by wavetylor** [testcontainers/testcontainers-java#1603]
Currently using the Localstack module is not possible in a situation where pulling public docker images is not possible. 

Testcontainer has a facility to address this, testcontainer.properties, but localstack doesn't take advantage of this. 

It would be excellent if this were the case!

**Comment by rnorth** [comment]
Hi @wavetylor. Sure! I think this would be fine.

If you'd like to raise a PR that would be great. I don't think there should be any serious gotchas. 

The only thing is that the tag/version part probably belongs in the `testcontainers.properties` override (i.e. you'd use the no-args constructor), but I expect that was probably your plan anyway.

Please have a glance over any Localstack related issues/PRs we have (e.g. #1504) so that you can get a sense of other forthcoming changes - not because it impacts this change directly, but more so you can be confident that we'll remain compatible with your custom image!

**Comment by wavetylor** [comment]
@rnorth sounds good. Already working on the changes.

**Comment by eddumelendez** [comment]
Nowadays, testcontainers support [image name substitution](https://www.testcontainers.org/features/image_name_substitution/) which solves issues like this.

@wavetylor feel free to reopen if I missed something.
