### ISSUE TITLE
Communication between containers

### ISSUE THREAD

**Issue by masterdany88** [testcontainers/testcontainers-java#1616]
How I can make containers to talk each other? Is there any simple solution for that?
How I can stop execution others containers before the first one (f.e.: db) will start?
Is this possible using vanilla testcontainers? Or should I use docker compose module here?

I have 4 services, they need to communicate. But I can not fetch port, as the first containers have not started in execution time of the following one. Please give me some hints.

**Comment by bsideup** [comment]
Hi. You already created two duplicating questions on Stack Overflow, and I answered one of them:
https://stackoverflow.com/questions/57036503/how-to-expose-port-from-container-to-container-on-testcontainers/57040795#57040795

Please, respect others' time and avoid posting your questions everywhere, because most probably the same people will be answering.
