### ISSUE TITLE
Postgres container fails in 1.12.0; app can not connect.

### ISSUE THREAD

**Issue by oneiros-de** [testcontainers/testcontainers-java#1678]
[This test](https://github.com/testcontainers/testcontainers-java/files/3442189/WiringITest.java.txt) works with 1.11.4, but fails with 1.12.0; [here](https://github.com/testcontainers/testcontainers-java/files/3442163/test-log.txt) is the log of the failed test run. 

Dependencies are up-to-date, i.e. Spring Boot 2.1.6 and JUnit 5.5.1 and AssertJ 3.13.0.

**Comment by bsideup** [comment]
> "spring.datasource.url=" + database.getJdbcUrl() + "?currentSchema=itest",

This assumes that the URL does not contain `?` already. Try replacing `?` with `&`, because, in 1.12.0, we set some query parameters already:
https://github.com/testcontainers/testcontainers-java/blob/2d11d80034c47f6d6538e036e77f50c0ede98018/modules/postgresql/src/main/java/org/testcontainers/containers/PostgreSQLContainer.java#L62

**Comment by oneiros-de** [comment]
Thanks; that works. Please in the future document such changes.

**Comment by bsideup** [comment]
we only document changes that affect the public API and/or the behaviour.

It is recommended to use the URL parsing libraries to avoid issues like that one, we only guarantee that the returned string will be an URL, and it is valid to have pre-set query parameters in URLs
