### ISSUE TITLE
Question: Is shading for jackson still relevant?

### ISSUE THREAD

**Issue by ali-nutmeg** [testcontainers/testcontainers-java#1732]
I can't see why we need to do shading on the jackson dependency.
Can someone explain this to me please?
Thanks.

**Comment by rnorth** [comment]
A long time ago, around the start of the project probably when I was the sole user, I experienced dependency version conflicts with Jackson. This was in a codebase that had Jackson on the classpath both via Testcontainers/docker-java and Dropwizard. I don’t recall the versions I’m afraid. 

I imagine it’s quite possible that the transitive dependencies have converged on compatible versions, so that in practice a conflict would be unlikely nowadays. However, I think I’d prefer not to expose people to that risk all of a sudden. 

Is this something you’re just curious about, or has the shading of Jackson caused you some problems?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ali-nutmeg** [comment]
Hi @rnorth 
Thanks a lot for taking the time to reply!

This is something I was curious about. When I saw the codebase, I couldn't see any reason for shading jackson. It would increase the size of the library too and introduce duplication.

From what I could see, docker-java (3.1.5) and dropwizard (1.3.14) have similar versions of jackson with only a minor version difference - 2.9.8 and 2.9.9 respectively.

**Comment by bsideup** [comment]
Our rule of thumb - shade everything that:
1) can be shaded (read - does not have native code)
2) does not appear in our public API

We do it to avoid version conflicts.
Also, docker-java and dropwizard are not the only consumers of Jackson (given it's popularity).

Did you have any issues with it, or it was just out of curiosity?

**Comment by ali-nutmeg** [comment]
Hi. 
It was just out of curiosity.
Thanks for the explanation

**Comment by rnorth** [comment]
Cool, let’s close then!
Thanks @ali-nutmeg 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
