### ISSUE TITLE
Can not start consul container with docker desktop 2.1.0.1 (engine version 19.03.1) on mac

### ISSUE THREAD

**Issue by deeptibaghel** [testcontainers/testcontainers-java#1739]
org.testcontainers.containers.ContainerLaunchException: Could not create/start container
 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:315)
 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:237)
 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
 	... 5 more
 Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://172.17.0.1:8500/v1/agent/self should return HTTP [200])
 	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:606)
 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:292)

**Comment by rnorth** [comment]
Hi @deeptibaghel 
I’m afraid that’s not much to go on. 

Do you think there is a bug in Testcontainers or do you need help using it?

Either way, please show the code that you’re using to run the consul container and the container’s logs. 

Thanks
Richard 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnrengelman** [comment]
I did some digging and it appears to be a race condition in the wait strategies when the container comes up. It's definitely  a race condition, as I can put a break point in and then the container will start successfully. If you change the HTTP Response wait to a port based wait strategy, it works fine as well.
It's somewhere in this code https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/strategy/HttpWaitStrategy.java#L145, but I couldn't debug it fully because of the de-lombok'd source jar that is published for this project.

**Comment by rnorth** [comment]
Hi @johnrengelman, do you have visibility of @deeptibaghel’s code? I’d really like to try and diagnose this, but I’d prefer not to have to start with a guess of how this is setup!

If there is a general timing bug then it’d still be good to start with a repro case that reliably triggers it, even if we later distil it down to something more generic. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnrengelman** [comment]
So the context is that there is a program that launches other containers to simulate an environment, with the main program also being packaged as a container and given `/var/run/docker.sock`  as a mapping so it can launch additional containers.  We only see the problem when the following code is invoked from within  a container that has `/var/run/docker.sock` mapped. (specifically  in this scenario, we  are initializing with `ephemeral=false`).

```
package com.target.platform.connector.test.consul.internal;

import com.target.platform.connector.config.internal.consul.Consul;
import com.target.platform.connector.config.internal.consul.ConsulConfig;
import com.target.platform.connector.exceptions.Exceptions;
import org.testcontainers.containers.FixedHostPortGenericContainer;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;

import java.net.URI;


public class DefaultConsulAdapter extends AbstractConsulAdapter {

  private GenericContainer<?> consulContainer;
  private static final String CONTAINER = "consul:1.1.0";

  public DefaultConsulAdapter(boolean ephemeral) {
    super();
    if (ephemeral) {
      consulContainer = new GenericContainer<>(CONTAINER)
        .withExposedPorts(8500);
    } else {
      consulContainer = new FixedHostPortGenericContainer<>(CONTAINER)
        .withFixedExposedPort(8500, 8500);
    }
    consulContainer = consulContainer
      .withCommand("agent -dev -client 0.0.0.0")
      .waitingFor(Wait.forHttp("/v1/agent/self").forStatusCode(200));
  }

  public URI getConsulUri() {
    return Exceptions.uncheck(() -> new URI(getConsulUrl()));
  }

  @Override
  public void start() {
    consulContainer.start();
    consul.set(new Consul(new ConsulConfig().address(getConsulUrl())));
  }

  @Override
  public void stop() {
    consul = null;
    consulContainer.stop();
  }

  @Override
  protected void before() throws Throwable {
    super.before();
    start();
  }

  @Override
  protected void after() {
    super.after();
    stop();
  }

  private String getConsulUrl() {
    return String.format("http://%s:%s", consulContainer.getContainerIpAddress(), consulContainer.getMappedPort(8500));
  }
}
```

So, in this scenario, the `consulContainer.getContainerIpAddress()` call is  resolving to  `172.17.0.1` (the `docker0` bridge), so  I  suspect what's happening is that the initial URL Connection is being made before the `consul` container has connected to the network, so the connection is routing to the host over the bridge instead of the container. It also appears that the `HttpWait` strategy itself is always resolving to the `docker0` bridge here: https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/strategy/HttpWaitStrategy.java#L211
