### ISSUE TITLE
Default Port Mapping Issues

### ISSUE THREAD

**Issue by KyleAure** [testcontainers/testcontainers-java#1807]
If I create a test container just using the default port for that container: 

```java
MSSQLServerContainer<?> sqlservercontainer = new MSSQLServerContainer<>().withLogConsumer(DatabaseContainerFactory::log);
```

Then `sqlservercontainer.getFirstMappedPort();` will return the port that is mapped to `1433`

If I create a test container and then later expose additional ports:

```java
MSSQLServerContainer<?> sqlservercontainer = new MSSQLServerContainer<>()
	.withEnv("MSSQL_RPC_PORT", "135")
	.withEnv("MSSQL_DTC_TCP_PORT","51000")
	.withEnv("MSSQL_AGENT_ENABLED", "true")
	.withLogConsumer(DatabaseContainerFactory::log);
			
sqlservercontainer.addExposedPort(135);
sqlservercontainer.addExposedPort(51000);

Log.info(c, "setupDataSourceProperties", "Port 1433 mapped to: " + sqlservercontainer.getMappedPort(1433));
Log.info(c, "setupDataSourceProperties", "First mapped port: " + sqlservercontainer.getFirstMappedPort());
```
I would expect that `sqlservercontainer.getFirstMappedPort();` and `sqlservercontainer.getMappedPort(1433);` would return the same value.  But the result is:

```
setupDataSourceProperties      I Port 1433 mapped to: 33867
setupDataSourceProperties      I First mapped port: 33868
```

**Comment by kiview** [comment]
This behaviour comes from the implementation of `MSSQLServerContainer` (and most specialized container classes will follow this pattern).

The MSSQL port 1433 is added in the `configure()` method of the container life cycle. So this means the default port is added after the ports you've added by hand.

I would not consider this a problem, since the normal way to interact with the container would be using `getJdbcUrl()`. Therefore I will close this issue for now.

If you can elaborate further why this is a problem for certain use cases, I'd be happy to reopen the issue.
