### ISSUE TITLE
TestContainers-Selenium - Support for other browsers

### ISSUE THREAD

**Issue by sazzer** [testcontainers/testcontainers-java#1933]
TestContainers WebDriver support is fantastic, and allows us to test our webapps in a real browser really easily at runtime. However, it's restricted to only Chrome or Firefox. It would be really useful if it could be expanded to other browsers as well - especially the ones that are the more problematic at runtime.

Specifically I'm thinking:
* Edge
* IE
* Android
* iPhone / iPad

I'm not sure that all of those have Selenium docker containers available though - which is, I assume, the reason they've not been added already?

**Comment by ManfredSchenkIOSB** [comment]
Just a comment: Edge and IE would require Testcontainers to run on a Windows Docker with Windows Containers, Android and iPhone/iPad would require those Browsers to run within a Linux environment since Docker is mostly linux-based.
So I think this request for additional browser support can not be fulfilled. (Although it would be great to have such support available)

**Comment by rnorth** [comment]
@ManfredSchenkIOSB thanks, I agree. The lack of Docker images for other browsers holds us back, and working on such images is outside the scope of this project I’m afraid. 

If somebody were to develop a Docker image for other browsers and contribute that to the seleniumhq project, then of course we would quite happily start using it. 

For now, though, I shall close this issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
