### ISSUE TITLE
PDF version of documentation hosted on github

### ISSUE THREAD

**Issue by Sammers21** [testcontainers/testcontainers-java#2033]
Nice to have if https://www.testcontainers.org/ is not aviliable.

**Comment by Sammers21** [comment]
web site is not available(or respond very slowly) now

**Comment by bsideup** [comment]
The website opens just fine. Please make sure that your ISP is not blocking it (roscomnadzor, I am looking at you :D)

**Comment by Sammers21** [comment]
@bsideup , it wasn't blocked. I have requested the site from a server located in Germany. Didn't work as well

**Comment by Sammers21** [comment]
Anyway, if something goes wrong with the web site, it would be awesome to have a PDF  version. For, example, PostgreSQL provides a PDF per each release.

**Comment by Sammers21** [comment]
@bsideup , what if I create a GitHub action which will render documentation and put it along with a release artifacts

**Comment by Sammers21** [comment]
@bsideup, ping

**Comment by rnorth** [comment]
Thanks for the offer to add automation for this, but I really think we’ll have to decline. The docs are always available in our GitHub repo, so even if our site were down, there’s still a pretty reasonable fallback. 

The site is hosted on Netlify and since last month is also proxied/cached by Cloudflare, so together ought to be pretty reliable and fast. 

An automated PDF version of the docs would be a cool thing for sure, but it’d become another thing for us to understand and maintain. As a tiny team of volunteers we have to try and keep focused, and unfortunately that means we sometimes have to say no to things.
