### ISSUE TITLE
Replace boot2docker with docker-machine

### ISSUE THREAD

**Issue by outofcoffee** [testcontainers/testcontainers-java#21]
Boot2Docker is being deprecated in Docker 1.8 in favour of the Docker Inc.-supported ``docker-machine``. See note on B2D Github here: https://github.com/boot2docker/boot2docker-cli#pending-deprecation

We should replace references to ``boot2docker`` with ``docker-machine``. Functionality is the same or better. Stability-wise it's fine on OSX, and a bit shaky on Windows (specifically 8.1).

**Comment by rnorth** [comment]
Agreed - seems like the time is right to switch over. We can technically support both; check for `docker-machine` on the path, and fall back to `boot2docker` if it's not found.

That'd be done here: https://github.com/rnorth/test-containers/blob/master/core/src/main/java/org/rnorth/testcontainers/containers/AbstractContainer.java#L234

Using this to check for presence/absence of the executables: https://github.com/rnorth/test-containers/blob/master/core/src/main/java/org/rnorth/testcontainers/utility/CommandLine.java#L48

**Comment by rnorth** [comment]
Technically, thinking this through a little further, we should be using environment variables as the first authoritative set of docker access credentials, falling back to the OS X compatibility tools only if that doesn't work. This would allow an OS X user to utilize any kind of external docker environment they want, but for users who don't care to set anything like this up we still have sensible defaults.

So I think the sequence should be:
* Attempt to connect to docker daemon using default settings/docker environment variables (e.g. DOCKER_HOST, using `DefaultDockerClient.Builder#fromEnv()`). If this fails, fall back:
* Attempt to discover docker using docker-machine if it's on the PATH
* Attempt to discover docker using boot2docker if it's on the PATH
* otherwise, fail loudly

Thoughts?

**Comment by swissarmykirpan** [comment]
Just having a look at this. Saw this bit of code:

https://github.com/testcontainers/testcontainers-java/blob/master/modules/selenium/src/main/java/org/testcontainers/junit/BrowserWebDriverContainerRule.java#L148

Looks like it an unused method - can you confirm. I'll clean it up then.

**Comment by rnorth** [comment]
> Looks like it an unused method - can you confirm

It's untested, but it should be present. The purpose of this is to provide a way of generating URLs that Selenium containers can talk to the developer's local machine on (since more often than not they'll be running the system under test there).

It was previously used in a test, but probably ought to have a new test created for it (perhaps a single-class Jersey app created just for the sake of testing this).

**Comment by outofcoffee** [comment]
@rnorth SGTM. Be aware that since ``docker-machine`` allows the creation of multiple machines, it's not just a replacement for B2D; theoretically the machine(s) you create could be running elsewhere. Maybe safer just to try the first item, then GOTO FAIL?

**Comment by rnorth** [comment]
Resolved with 0.9.8 release.
