### ISSUE TITLE
Organisation? Roadmap?

### ISSUE THREAD

**Issue by swissarmykirpan** [testcontainers/testcontainers-java#23]
I've started working on a version of this for .NET. Would be good to start to put together documentation around what TC delivers right now and then future work as well.

Time to turn it into a github organisation? @rnorth

**Comment by rnorth** [comment]
Yup, cool! Will try and set this up over the weekend.

**Comment by rnorth** [comment]
OK, this is in progress:
* Github org is set up: https://github.com/testcontainers/
* testcontainers.org is purchased and set up; basic DNS and mail, no website. We need this at a minimum to use the org.testcontainers prefix in maven central.
* will migrate this project over to the organisation next

**Comment by rnorth** [comment]
Please note that I've switched ownership of the repo _and_ renamed it to testcontainers-java. New URL is: https://github.com/testcontainers/testcontainers-java

**Comment by swissarmykirpan** [comment]
How about testcontainers.io ?

**Comment by swissarmykirpan** [comment]
Happy to go half way with the costs in regards to all of this btw :)

**Comment by rnorth** [comment]
Cheers! If you want to chip in a :beer: sometime would be more than generous enough ;)

I went for testcontainers.org basically because it was readily available, plus org.* is more common in java package naming than io.* so looks less jarring.

Next steps: 
* rename all the source packages and POM groupIds
* release via bintray and maven central (probably v0.9.6)
* update docs and add roadmap
* when you're ready, set up a testcontainers-dotnet (name?) repo under the org
