### ISSUE TITLE
Missing privileged support for docker container

### ISSUE THREAD

**Issue by Jojo255** [testcontainers/testcontainers-java#234]
While I was using the GenericContainer I found a problem using it. There is the privileged option missing. Since I'm using a IBM DB2 in project in a docker container, I need that support of docker.

**Comment by rnorth** [comment]
Hi @Jojo255 
Thanks for this - good idea!
Richard

**Comment by bsideup** [comment]
@rnorth I see implementation and feel that we really should move to 2.0 and traits :)

**Comment by Jojo255** [comment]
@bsideup @rnorth 
Do you have any clue why the circleci build has failed? Haven't changed anything there and I think I didn't destroyed anything :-D

**Comment by rnorth** [comment]
Sadly we have a couple of flapping tests that fail more frequently on CircleCI - it's likely to be one of those :(
I need to address when I have a bit of time...

**Comment by Jojo255** [comment]
@rnorth 
Is there a roadmap for 2.0 or any plans when it should be released or the work get's started

**Comment by rnorth** [comment]
@Jojo255 thanks for this, and sorry for taking such a long time to respond. This PR looks good to me so I'll merge. The Circle CI failure is, unfortunately, random and I'm thinking of disabling that for CI (Travis is serving us a bit better).

Re 2.0, I think @bsideup was suggesting that this change is good justification for something we want to do in 2.0, but it doesn't have to wait until 2.0. I'm not sure about 2.0 release timeframe - likely early next year rather than this year.

I'll merge and try and release ASAP, though.

**Comment by rnorth** [comment]
Released in 1.1.7 - sorry for the delay in getting this out.
