### ISSUE TITLE
How to launch containers on distinct docker hosts in one test

### ISSUE THREAD

**Issue by peterbollen** [testcontainers/testcontainers-java#237]
Not sure if the right place, but I would like some advice on how to launch container X on docker host A, and container Y on docker host B in one test.

My current approach was trying to define two chaining class rules.

Each chain consisted of one rule that sets up the corresponding DOCKER_HOST system property, and another rule that started the container.

However that container was always started against the default DOCKER_HOST, because each rule is created before the actual chain of rules is executed + when a container rule is created, the docker client is already initialised

Any advice?
Thanks!

**Comment by peterbollen** [comment]
Atm I forked this repo and added some code so you can pass the dockerhost ip in when constructing the rule. 

Interested in a PR?

**Comment by rnorth** [comment]
Hi @peterbollen 
I'm really sorry for the slow response. This use case wasn't one I'd ever envisaged to be honest, so that's why it's not supported right now!

I think we could probably accept a PR to add this, thanks! From my perspective I think it would fit in best and be most reusable if we:

- use the existing `DockerClientProviderStrategy` system to test and use the rule-specific configuration. i.e. subclass `DockerClientProviderStrategy` and use that to help check and build the docker client
- probably allow TLS configuration (at a minimum, enabled flag and certificate path) to be optionally set by the user, in addition to the docker host URI. I'm wondering whether accepting a param of type `DockerClientConfig` might be the best way to do this - it's probably the most comprehensive and flexible approach.

What do you think?

Thanks

Richard

**Comment by peterbollen** [comment]
Hi @rnorth 

Thanks for the feedback. My current changes are in line with you suggestions.

I'll create a PR once I got more time to work again on this. Keep you posted.

Greetings,
Peter

**Comment by peterbollen** [comment]
Hi @rnorth. Here' update on this one. 

In the end we didn't need this kind functionality In our tests anymore. 

I favor not merging this in, as there is no usecase :-)

Thanks for the advice!
