### ISSUE TITLE
Add support for $HOME/.docker/config.json

### ISSUE THREAD

**Issue by tourea** [testcontainers/testcontainers-java#247]
The current version (1.1.7) hardcodes the private registry authentication file to use ($HOME/.docker/.dockercfg). It would be nice to add support for $HOME/.docker/config.json.

**Comment by rnorth** [comment]
Hi Aboubacar
That seems sensible, thanks for suggesting. If you or anybody else would
like to raise a PR it would be most welcome!

Would it perhaps make sense to check for the existence of the config.json
file and use that first, falling back to dockercfg otherwise? I'd like
Testcontainers to select a sensible default rather than the user having to
inform the tool which file to look at.

Thanks

Richard

**Comment by tourea** [comment]
@rnorth I've opened a PR to resolve this issue (https://github.com/testcontainers/testcontainers-java/pull/270)
