### ISSUE TITLE
Unexpected end of file error when accessing service started by GenericContainer 

### ISSUE THREAD

**Issue by Dhivyaa21** [testcontainers/testcontainers-java#2517]
I am using GenericContainer to start a service in a docker container. When accessing the service on the exposed port from the host system using http, the client throws an "Unexpected end of file error". Looks like the docker container is shut down before the service could serve the request?

`GenericContainer service= new GenericContainer(new ImageFromDockerfile()
            .withDockerfile(Paths.get(DOCKER_FILE.getPath()))
            .withBuildArgs(BUILD_ARGS))
            .waitingFor(Wait.forHttp("/").forStatusCode(200))
            .withLogConsumer(new Slf4jLogConsumer(logger))
            .withExposedPorts(8000)`

The service is accessed on - `"http://" + service.getContainerIpAddress() + ":" + jenkinsImageWithPlugins.getMappedPort(8000)`

**Comment by valvolt** [comment]
I've had the same problem on Ubuntu, and... When logging, it appears that getContainerIpAddress() returns "localhost" instead of the actual IP address.

If I log the content of the object itself I can see its property "ipAddress" set properly, but there does not seem to be any way to get this IP address via an object method.

**Comment by valvolt** [comment]
Dirty workaround:

      // Dumping GenericContainer data
      String serviceinfo = service.toString();

      String pattern = "ipAddress=[0-9\\.]+";
      String ipAddress = "";

      // Create a Pattern object
      Pattern r = Pattern.compile(pattern);

      // Now create matcher object.
      Matcher m = r.matcher(serviceinfo);
      if (m.find( )) {
        // m.group(0) will be in the format: ipAddress=172.19.0.5
        // stripping the first 10 chars to keep the IP address only
        ipAddress = m.group(0).substring(10);
      }else {
         logger.error("Could not retrieve IP address!");
      }

Then use ipAddress instead of service.getContainerIpAddress()

**Comment by bsideup** [comment]
@valvolt your problem is unrelated to this issue.

Also, as stated in the `getContainerIpAddress()`'s javadocs, it returns an address accessible from the test host, hence "localhost" on your machine. If you need to access the container from another container, you should use Docker Networks:
https://www.testcontainers.org/features/networking/#advanced-networking

**Comment by bsideup** [comment]
@Dhivyaa21 in your code, you use `service.getContainerIpAddress()` but `jenkinsImageWithPlugins.getMappedPort(8000)`. Shouldn't it be `service.getMappedPort()`?

**Comment by Dhivyaa21** [comment]
@bsideup  yes you are correct. But that was not the problem. This was a weird issue because it occurred only in few machines not all the ones. Only the POST requests to the service were returning unexpected end of file error. It was very hard to reproduce this error. However, I got this working by increasing the startup timeout of the container and using a different client implementation.

**Comment by Dhivyaa21** [comment]
Fixed it with custom client implementation and increasing the container timeout.
