### ISSUE TITLE
Registry authConfig including plain text credentials logged on startup

### ISSUE THREAD

**Issue by Faradax** [testcontainers/testcontainers-java#2626]
On container startup, credentials are logged plain text:
![image](https://user-images.githubusercontent.com/5133378/80351408-8e1aed00-8872-11ea-82cd-18e886d18904.png)

There is another variant of this, where the "auth"-field in this log contains a base64 version of the same information. I believe the entire "authConfig" should be omitted from logging.
Tested with Testcontainers 1.14.1.

I am aware that this log originates from an upstream dependecy of testcontainers, but I am still openening this here as I think that these kinds of logs should probably be disabled by default in testcontainers - also, docker-java has argued here that they won't fix it: https://github.com/docker-java/docker-java/issues/1125

**Comment by bsideup** [comment]
Hi @Faradax,

This is indeed from docker-java, and, since I am the new maintainer of it, I'd say we should fix it there :)

Logging command's body isn't the best approach (or it should AT LEAST be moved to TRACE), since commands like `CreateContainerCmd` may also contain sensitive environment variables.

Do you mind re-reporting it there?
