### ISSUE TITLE
Testcontainers MockServer module incomplete documentation

### ISSUE THREAD

**Issue by javiertoja** [testcontainers/testcontainers-java#2710]
Hi, 

Inside the official documentation of the [mock server module](https://www.testcontainers.org/modules/mockserver/) appears the use of a class not bundled within the module (MockServerClient), the nexus artifact do not contain this class and after looking on the examples on this repository i found that it is imported from 

```<!-- https://mvnrepository.com/artifact/org.mock-server/mockserver-client-java -->
<dependency>
    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-client-java</artifactId>
</dependency>
```

Please, could you consider to update the documentation to reflect that the client is not bundled with the server. Or include the client also inside the testcontainers mock server artifact.

**Comment by bsideup** [comment]
Testcontainers' MockServer module is just a helper to start the container with MockServer. It does not implement the mocking itself (nor the server), and it is expected that the user will bring the client (as with any other module).

Since these expectations are common for a Java library, I don't think mentioning this in the docs is a good idea.

@rnorth WDYT?

**Comment by JordiGarcL** [comment]
I actually believed this too. I don't think mentioning would make any harm. What about just putting an hyperlink to [maven](https://search.maven.org/search?q=mockserver-client-java) on the MockServerClient word?
