### ISSUE TITLE
Fallback for quay.io

### ISSUE THREAD

**Issue by 2ndalpha** [testcontainers/testcontainers-java#2763]
quay.io is down:
> com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/testcontainers/ryuk/manifests/0.2.3: received unexpected HTTP status: 500 Internal Server Error"}

Testcontainers should not depend on one registry, there should be a fallback.
Having single-point of failure for a service we don't have control over seems like a big oversight.

**Comment by mpdn** [comment]
It'd be nice to be able to fall back on locally cached data in situations like these as well.

**Comment by bsideup** [comment]
Although I understand the pain, it is not really Testcontainers' fault.

We do fallback to locally available image. One can override the image as well:
https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper

Last but not least, check Docker's available options for dealing with registry issues.

Also FYI we're considering migrating to Docker Hub, so that the registry mirroring can be used (it only works for images on Docker Hub)

**Comment by 2ndalpha** [comment]
> Although I understand the pain, it is not really Testcontainers' fault.
It is a design choice, redundancy should be built in.

Falling back to local image in CI is not a solution.

Closing the issue just creates frustration in the community.
That's how you get forks 🤷‍♂️

**Comment by mpdn** [comment]
>We do fallback to locally available image.

I can see that running on a machine with the image cached actually works. I mistakenly thought the other machine had a cached image.

**Comment by bsideup** [comment]
@2ndalpha threatening FOSS projects with "forks" does not help the community either.

I've provided enough info about the situation, let you know that we're considering migrating to another provider, and gave advices how to workaround it for now.
There is no point in keeping this issue open since we (the Testcontainers project) can't fix Quay's downtime, and the releases that depend on that image are already there, so we can't magically update them post factum.

**Comment by 2ndalpha** [comment]
@bsideup that is not a threat, just stating the fact that suppressing the dialog leads to frustration.

> There is no point in keeping this issue open since we (the Testcontainers project) can't fix Quay's downtime
But you can build in a fallback to another registry.
Closing the issue when the problem is not solved is not solution.

**Comment by bsideup** [comment]
@2ndalpha 

> But you can build in a fallback to another registry.

Feel free to use *any* registry you want, as I previously mentioned:
https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper

> Closing the issue when the problem is not solved is not solution.

The problem is solved by:
1. using the local cache
2. allowing the users to override the image
3. publishing Ryuk's sources, so that anyone can build it: https://github.com/testcontainers/moby-ryuk

Also, as a follow up, we're making another attempt at getting `testcontainers` org at Docker Hub. If fails, we will use another name.

> Closing the issue when the problem is not solved is not solution.

Falling back to another registry (which one, btw?) isn't an option, hence closed issue. See provided alternatives on how to workaround it (for now), and stay tuned for future improvements in this area. That's it.

**Comment by 2ndalpha** [comment]
> Feel free to use _any_ registry you want, as I previously mentioned:
> https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper
Really don't want to but probably have to.
Quay is down again.

**Comment by wirzko** [comment]
We are running our tests with github actions, TESTCONTAINERS_RYUK_DISABLED=true ist the solution since we don't a cleanup.

**Comment by 2ndalpha** [comment]
Re-published the image to Docker Hub: `qminder/moby-ryuk`

**Comment by alvarosanchez** [comment]
I think this problem manifests especially in a CI environment, where the environment is fresh, like @wirzko mentioned, in which case `TESTCONTAINERS_RYUK_DISABLED` should be set to true anyway since there is no benefit of doing a cleanup.

And locally it should use the cached image. 

So I don't see this problem being particularly important, and not worth the threatening tone of some comments, considering that the Testcontainers team has quickly replied to the concerns of the original poster.

@bsideup thank you and the rest of the team and keep up with the good job you guys are doing!

**Comment by bsideup** [comment]
@alvarosanchez thank you! Really appreciate your support :)

Seeing our users struggling because of something we can't fix (#hugops to Quay, btw :D) is the worst, but we're doing our best to migrate to Docker Hub, which may not have 100% uptime, but at least can easily be mirrored (only Docker Hub images can be, custom registry mirrors are not (yet?) supported by Docker)

As with any other downtime (oh gosh, why knew we would need to do a downtime post mortem... of a library 😂 ), we're taking notes and actions. I am excited about some of them because they not just fix the problem related to Quay, but also bring new functionality that will help diagnostic the failures.

And, for those who need to fix it now now, we're almost done with the Docker Hub:
http://hub.docker.com/r/testcontainersofficial/
... than you can override with:
https://www.testcontainers.org/features/configuration/#customizing-images

**Comment by varpa89** [comment]
Cool I found this issue =) Did not immediately understand why builds via GitHub actions are falling

**Comment by jrmcdonald** [comment]
@bsideup Thanks the work that you're putting in to get Docker Hub up and running! What is the best place to watch/way to find out when the image pushed to Docker Hub is ready?

**Comment by bsideup** [comment]
@jrmcdonald I will post an update in this issue. You can also subscribe to #2805's notifications

**Comment by bsideup** [comment]
FYI Testcontainers 1.14.3 is out and now uses Docker Hub instead of Quay.io.
I hope it will be stable enough to not have to get back to this topic for some time 😅
