### ISSUE TITLE
Improvement customizing image for Postgres DB module.

### ISSUE THREAD

**Issue by avwsolutions** [testcontainers/testcontainers-java#2764]
We are currently using the Postgres DB module. This module is great and does the job.

Today we found out it depends on Docker hubs for retrieving the container image. We wanted to change this like we did with the *ryuk.container.image* , but found out this is hardcoded and only allows to set the tag. It would be great if we can configure our own docker registry or image URL, just like the Customizing images feature, see [Features](https://www.testcontainers.org/features/configuration/)

like postgres.container.image = ourhub/postgres:11.8

Can you make the module image / repo also configurable, just like you support this for other container images like ryuk, kafka or localstack ?

**Comment by bsideup** [comment]
Have you considered mirroring the Docker Hub as described here?
https://www.testcontainers.org/features/configuration/#customizing-images

**Comment by avwsolutions** [comment]
Hi @bsideup , thanks for your quick reply. We also looked into that possibility. But since we have a rather small environment, it seems not to be a feasible solution.  Again we can still go for this in the future, but image parameter looks much simpler to manage.

Hopefully you understand this.

**Comment by pcazzola** [comment]
Not to say the feature request for a property isn't valid, but if you are just looking for how to use a different postgres image you should be able to specify it when you create the container.

For example, change this:

PostgreSQLContainer<?> pg = new PostgreSQLContainer<>();

To this:

PostgreSQLContainer<?> pg = new PostgreSQLContainer<>("ourhub/postgres:11.8");

This option isn't available for the Ryuk container because it is constructed under the hood.
