### ISSUE TITLE
Copy directory doesn't work with 'ImageFromDockerfile.withFileFromPath(...)'

### ISSUE THREAD

**Issue by tourea** [testcontainers/testcontainers-java#285]
In my Dockerfile, I have something similar to:
`COPY ./folder /path/to`, where `folder` is a directory. 
When I try to start a generic container (using `ImageFromDockerfile`), I get an exception in ImageFromDockerfile:

```
Caused by: java.lang.RuntimeException: Can't transfer file ...
  at org.testcontainers.images.builder.traits.FilesTrait$1.transferTo(FilesTrait.java:43)
  ...
Caused by: java.io.IOException: Is a directory
```

**Comment by rnorth** [comment]
Ouch - sorry. Let's try and solve this with #279, which gives us a good chance to clean up file/resource handling for good.

**Comment by rnorth** [comment]
Hi @tourea 
Sorry it's taken a while to give you an update on this - it's turned out quite a bit harder than I initially thought. However, I have some draft code on a [branch](/testcontainers/testcontainers-java/blob/285-recursive-tar-copy) which allows recursive copying of files in.

You can see an example [here](https://github.com/testcontainers/testcontainers-java/blob/285-recursive-tar-copy/core/src/test/java/org/testcontainers/utility/DirectoryTarResourceTest.java).

I'll keep working on this and tidying up - if you really want to try it in the meantime you could use jitpack to obtain a branch build (https://jitpack.io/#testcontainers/testcontainers-java/285-recursive-tar-copy-SNAPSHOT should work)

@bsideup FYI - this branch is too messy to deserve review yet. However, you might want to know that (so far) I had to make some fairly big changes to [`Transferable`](https://github.com/testcontainers/testcontainers-java/compare/285-recursive-tar-copy?expand=1#diff-6161ac509de845c533b80b8de8955db6) to allow enough flexibility for recursively populating the context TAR. I will make some further changes to the interface hierarchy, but thought I should give you a heads-up.

Richard

**Comment by rnorth** [comment]
[This change](!313) is getting closer to being ready; I'd hope to get it released soon. Sorry for the long wait on this.

**Comment by dbyron0** [comment]
The 'This change' link in your comment (https://github.com/testcontainers/testcontainers-java/issues/!313) doesn't work for me.  [This one](https://github.com/testcontainers/testcontainers-java/pull/313) does though.

**Comment by rnorth** [comment]
Support for this was added in #313 so I shall close.
