### ISSUE TITLE
Allow remote execution

### ISSUE THREAD

**Issue by MrBuddyCasino** [testcontainers/testcontainers-java#2855]
I'd like to run Docker remotely on a beefy desktop machine, and run the IDE on my laptop. This works fine with docker-compose with a simple SSH session and port forwardings, but testcontainers use random ports. 

I would like to have support for fixed ports, depending on a setting in `testcontainers.properties`. I could implemented it myself if you don't totally hate the idea.

Or maybe there is another way to achieve this?

**Comment by bsideup** [comment]
Testcontainers already supports remote Docker execution (just make sure you're not using the file system binds).

Regarding the fixed ports, we do not like them in general. You will find some of the motivation in this blog post:
https://bsideup.github.io/posts/testcontainers_fixed_ports/

You may experiment with doing port forwarding, but some containers (like Kafka) simply won't work due to the way the underlying technology works. What makes it even harder is that fixed ports on your machine may not match fixed ports on the remote one.

Since there is no universal approach that will work for everyone, I don't think this is something that can be added to Testcontainers, unless you have some cool idea how to make it work everywhere :)

/cc @rnorth

**Comment by MrBuddyCasino** [comment]
> Testcontainers already supports remote Docker execution
I see there is `EnvironmentAndSystemPropertyClientProviderStrategy`, its even configurable via `docker-java.properties`, very nice!

I'm thinking that I could simply use a Tailscale VPN between my machines, that way I don't have to forward single ports. The problem with that is that the Windows Docker Desktop daemon port only listens to 127.0.0.1, if I could only make it listen on all interfaces or at least the private Tailscale IP my problem would be (probably) solved. 🤔

**Comment by rnorth** [comment]
Yeah, I agree with @bsideup - fixed ports are such a false economy, and there's almost always a better solution to be found.

I definitely understand your pain and motivation though, as someone with an underpowered laptop 😁 

> I'm thinking that I could simply use a Tailscale VPN between my machines, that way I don't have to forward single ports

That's a good idea - basically anything that lets you access any of the docker host's ports, but without the security downsides of opening it up to the world.

> The problem with that is that the Windows Docker Desktop daemon port only listens to 127.0.0.1

This is possibly a tricky issue... The docker daemon is already basically running in a VM with Docker for Windows doing some clever on-the-fly port forwarding. I'm not sure whether its possible to expose these containers to Tailscale that's running on the Windows side. If that didn't work, I wonder if running Tailscale in docker on the host network might...

It would be interesting to hear how this goes, but to be honest I don't think that there will be a change to Testcontainers to support this use case. I hope that makes sense - please do keep us informed as I'm quite curious.

**Comment by MrBuddyCasino** [comment]
Alright, I think I've cracked it! 
This is my setup for macOS as a client and Windows 10 as a docker host:

On the Mac:
`~/.testcontainers.properties`
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy

`~/.docker-java.properties`
DOCKER_HOST=tcp://Tailscale IP:2375
DOCKER_TLS_VERIFY=0

On Windows:

Run in an elevated command prompt to forward pakets from the Tailscale IP to local Docker:
`netsh interface portproxy add v4tov4 listenport=2375 connectaddress=127.0.0.1 connectport=2375 listenaddress=<Tailscale IP> protocol=tcp`

Enable "Expose daemon" in Settings > General in Docker Desktop on Windows.
Disable Firewall for private networks (I'm behind a NAT router anyway).

Tada! I still can't believe it works.

**Comment by MrBuddyCasino** [comment]
Posted this on SO, its easier to find there and and might reduce the number of GH issues opened by dudes like me: https://stackoverflow.com/questions/62298539/

**Comment by rnorth** [comment]
Wow, that's really quite cool. Thanks for sharing your solution!

**Comment by Swy75** [comment]
Hello,
I'm trying to run testcontainers on a GCP VM from my local machine.
I followed instructions given here but I get : 
**EnvironmentAndSystemPropertyClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause SocketTimeoutException (connect timed out)**

Local machine :

-  .testcontainers.properties :
     docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy

-  .docker-java.properties :
    DOCKER_HOST=tcp://X.X.X.X:2375
    DOCKER_TLS_VERIFY=0

- testcontainers version : "com.dimafeng" %% "testcontainers-scala-scalatest"     % "0.39.5" % "test"
- MAC OS (M1 chip) 

GCP VM : 

  - is configured to allow all incoming traffic.
  - docker deamon is launched with this command :  sudo dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &

From my local machine I can access to the remote docker deamon throught nmap command.

Do you have any idea to solve this please ?
