### ISSUE TITLE
Compose container waitingFor does not work

### ISSUE THREAD

**Issue by Mingela** [testcontainers/testcontainers-java#2879]
Hello folks!

I faced the issue using testcontainers 1.10.2. waitingFor does not work. Totally.
I tried many approaches but the only successful one is to use the most recent version which is 1.14.3.

I used `.withLocalCompose(true)`

The next log output line (related to the test code) has appeared immediately after `Docker Compose has finished running`. I tried all of the relevant waiting strategies and none helped:
- Host & port
- Log output
- Dummy implementation with forced `Thread.sleep()`

Btw I've got another suggestion to treat `withStartupTimeout` together with `waitUntilReady` if that'd been set before `start()` invoked since as I can see now `waitUntilServiceStarted` does not care about the timeout. (like to merge such behavior into `AbstractWaitStrategy` to wait for the timeout before applying the actual `waitUntilReady` implementation)

So the issue is about the suggestion and the question about possible cause for 1.10.2 incorrect behavior. Moreover, after switching to 1.14.3 I've got an error 'container_name is not supported' but it worked with 1.10.2 that is also interesting.
Thanks.

p.s. tried on Kotlin 1.3.10 if it matters

**Comment by rnorth** [comment]
Hi @Mingela 

1.10.2 is pretty far behind - it’s not all that surprising that there are bugs that have been fixed in later releases, and we can’t support old versions.

Please could you upgrade?

Newer versions do not allow use of `container_name` because it conflicts with providing isolation between test runs. There aren’t normally any strong reasons to set that value, so hopefully it’s something you could remove from your compose file.
