### ISSUE TITLE
DockerComposeContainer strategy that waits on an endpoint in another container

### ISSUE THREAD

**Issue by ekis** [testcontainers/testcontainers-java#2923]
I am trying to understand if there is a way to configure a waiting strategy such that one container waits until another one returns an expected HTTP status code.

The containers are run as local compose containers and right now, I am using a curl script to do this check (one that I was hoping to eliminate by using this library).

Here is a code excerpt of how I imagine it would look like:

``` 
new DockerComposeContainer<>(Paths.get("./docker-compose.yml").toFile())
            .withLocalCompose(true)
            .withPull(true)
            .withExposedService(Service.CLOUD_DISCOVERY.name, Service.CLOUD_DISCOVERY.port)
            .withExposedService(Service.CLOUD_CONFIG.name,
                Service.CLOUD_CONFIG.port,
                Wait.forHttp("http://localhost:8761")
                    .forStatusCode(200)
                    .withReadTimeout(Duration.ofSeconds(15))
            )
            .withServices(
                Service.CLOUD_DISCOVERY.name,
                Service.CLOUD_CONFIG.name
            )
            .withLogConsumer(Service.CLOUD_DISCOVERY.name, new Slf4jLogConsumer(LOGGER))
            .withLogConsumer(Service.CLOUD_CONFIG.name, new Slf4jLogConsumer(LOGGER))
            .start();
```

I could not figure out if this exists from the docs and all my efforts to make this work have not been successful - so before I dive deeper into the code, I would like to ask:
- am I missing some part of configuration?
- is the HTTP url expected the one as seen from internal to the container host or external to the host (assumption is the latter)?
- if not, is this is even supported/envisioned as a strategy or this would need to be added in?

Thank you.

**Comment by rnorth** [comment]
Hi @ekis 
I'm afraid I think we're unlikely to do this - our intention is that the docker compose support should be able to reuse an existing working setup. If I understand this right, if the containers need to wait midway through the compose environment being `up`ped, then this is no longer a working standalone compose setup.

If that's the case, we'd encourage you to either do this purely inside of compose (e.g. per [this guide](https://docs.docker.com/compose/startup-order/)) or, if it's possible for you to do so, purely in Java using `GenericContainer` rather than Testcontainers' Docker Compose support.

Does that make sense?
