### ISSUE TITLE
Allow user to customize sid on OracleContainer

### ISSUE THREAD

**Issue by bsofiato** [testcontainers/testcontainers-java#3185]
Hi guys,

How you guys feel about adding the ability to set the sid on the OracleContainer?  I am thinking about using the same method as the username and password (i.e., adding a "withSid" method). If you guys think it is worth it, I can submit a PR for that.

**Comment by KyleAure** [comment]
I believe as of right now testcontainers only supports the express (XE) versions of oracle as they are the only "lightweight" versions available as docker images.  I use lightweight in quotes because they still end up being ~10GB, production level oracle images are even larger.  It would not make sense to support bringing up a production oracle image for testing. 

As such, the only SID available within the express image is "XE"
We do, however, have a pending issue to allow for use of service names to support pluggable databases here: https://github.com/testcontainers/testcontainers-java/issues/2215

**Comment by bsofiato** [comment]
We were able to run an oracle image (standard version) with test containers without any problem (we had only to change the share memory). It was a legacy system on which we had a test fixture already in place on this particular version. Nonetheless, I feel that ours is a corner case. 

In the meantime, I will take a look at the issue you mentioned.

Thanks for the reply

P.S. I don't know if it is me or you that closes this issue.

**Comment by KyleAure** [comment]
I believe you should be able to close the issue since you authored it.  I am just a contributor so I am unable to do so.
