### ISSUE TITLE
Proposal: Containerised DB for production

### ISSUE THREAD

**Issue by outofcoffee** [testcontainers/testcontainers-java#34]
In README.md there are two usage scenarios described, one of which is:

> Containerized database using a specially modified JDBC URL: after making a very simple modification to your system's JDBC URL string, TestContainers will provide a disposable stand-in database that can be used without requiring modification to your application code.

Imagine using a similar mechanism to spin up a persistent DB instance, or for that matter a Redis container, with the intention that it serves as a fast in memory cache. Both of these examples could be production use cases. 

Taking this even further, with the changes coming to Docker Networking with *libnetwork* in 1.8 and beyond, these wouldn't even have to be on the same server, as their lifecycle could be orchestrated on a separate node via Swarm/Kubernetes/Mesos etc.

In this way an application could theoretically instantiate its own dependencies; like an inside-out Docker Compose.

Thoughts?

**Comment by outofcoffee** [comment]
Two related thoughts:
* Ability to name containers
* Ability for a container to outlive the application/JVM process from which it is started

**Comment by rnorth** [comment]
Yes, sounds like an interesting idea and something I'd like to help out with. I think it probably deserves its own project, but perhaps there's a fair amount of testcontainers that could be factored out into a common dependency library. My rationale is that I'd like to keep TC reasonably constrained on scope and ambition, otherwise it'll never be finished ;)

Re the second two points:
* Yes, definitely should do it
* Yes, it's easy enough to make this opt-in so let's do it.
Both of these, I think, are prereqs for doing more sophisticated things with DB containers, especially around snapshot-restore and my pet ulterior motive (enabling this without H2: http://blog.jooq.org/2014/06/25/flyway-and-jooq-for-unbeatable-sql-development-productivity/)

**Comment by rnorth** [comment]
Some more things to think about:
* does having the Java app bootstrap its own dependency storage layer create some relatively unique partition/split-brain problems? What's going to be a good way to limit impact/prevent this?
* The 'tc'-in-the-URL trick with JDBC drivers is fun and works well with JDBC to allow us to create a proxy driver with associated container. That's fine for JDBC which has this convenient extension mechanism, but not so good for other useful resources (I'd _love_ to be able to do this with Redis, Elasticsearch, RabbitMQ, etc, etc..). What would be the alternative model for these instead? I think there's going to be a degree more intrusiveness into the application to permit this.
* There are a couple of convenient things we're doing that depend on containers being local (namely, grabbing videos of selenium sessions and in the future, perhaps some part of DB snapshotting). This reliance on the locality of the containers is mainly due to my laziness, but what can/should we do to allow remote containers? Maybe it's easy, or maybe it's a good reason to divide the project along dev-test/prod lines.

Keen for your thoughts!
Cheers
Rich

**Comment by rnorth** [comment]
I'll park this one for discussion over a :beer: some time ;)
