### ISSUE TITLE
Breaking change in CockroachDB CLI interface for versions 20.2+.*

### ISSUE THREAD

**Issue by lbialy** [testcontainers/testcontainers-java#3571]
Hi,

I have tried using versions 20.2.0 and 20.2.2 of CockroachDB with CockroachContainer and sadly the container crashes with the following output:

```
ERROR: no --join flags provided to 'cockroach start'

HINT: Consider using 'cockroach init' or 'cockroach start-single-node' instead

Failed running "start"
```

Testcontainers itself hangs on this log line:

`[2020-12-08 17:27:02,603] [INFO] [🐳 [cockroachdb/cockroach:v20.2.0]] [] [ScalaTest-run] - Waiting for database connection to become available at jdbc:postgresql://localhost:32830/postgres?reWriteBatchedInserts=true using query 'SELECT 1' MDC: {}` 

but doesn't fail even though the container itself is EXITED(1). It then assumes everything is fine and continues the test framework execution.

**Comment by giger85** [comment]
Since v20.2, below command is not working.
https://github.com/testcontainers/testcontainers-java/blob/c3a8ca76d0ed69f71c94e5bc2f7f1e0eef1a2259/modules/cockroachdb/src/main/java/org/testcontainers/containers/CockroachContainer.java#L56

According to v19.2 document, `start-single-node` command works.
- https://www.cockroachlabs.com/docs/v19.2/cockroach-start-single-node
> New in v19.2: This page explains the cockroach start-single-node command, which you use to start a single-node cluster with replication disabled. A single-node cluster is all you need for quick SQL testing or app development.

So, `start` command need to be fixed.

**Comment by giger85** [comment]
According to [release-support-policy](https://www.cockroachlabs.com/docs/releases/release-support-policy), current default tag (v19.1.1) can not be supported assistance.
- Assistance Support ends (EOL Date) v19.1: 11/1/20
