### ISSUE TITLE
Facing image not found issue in arm64 platform 

### ISSUE THREAD

**Issue by odidev** [testcontainers/testcontainers-java#3580]
I was trying to build the dubbo package for arm64 and found that there were test failures due to the jetcd package which  further depends on  testcontainers.

I found that the jetcd is using the **testcontainers-1.15.0**.  The failure was taking place as the [testcontainers ](https://github.com/testcontainers/testcontainers-java/blob/1.15.0/core/src/main/java/org/testcontainers/DockerClientFactory.java#L66)are using alpine:3.5 as **TINY_IMAGE**. If we update that image to **alpine:latest** then it is working fine with **1.15.0** release. 

It will be helpful if this release contains the above change.  If required I will raise the PR for the same.

**Comment by bsideup** [comment]
@odidev `alpine` isn't the only image that we're using that would fail on arm64. Ryuk is another example. So, officially, arm64 is not supported by Testcontainers.

Since `alpine` is only used for the system checks, you can disable them:
https://www.testcontainers.org/features/configuration/#disabling-the-startup-checks
