### ISSUE TITLE
TetstcontainerConfiguration has inconsistent properties resolving solutions

### ISSUE THREAD

**Issue by yingkun-bai** [testcontainers/testcontainers-java#3612]
Hello!

I put a testcontainers.properties in the classpath, e.g. src/test/resources/testcontainers.properties
checks.disable=true
However, I found it didn't work. While putting the same value in ~/.testcontainers.properties gets things done. 

After checking the source code, I found two get property methods:
- getEnvVarOrUserProperty => getConfigurable(propertyName, defaultValue, userProperties);
- getEnvVarOrProperty => getConfigurable(propertyName, defaultValue, userProperties, **classpathProperties**);

However
```
    public boolean isDisableChecks() {
        return Boolean.parseBoolean(getEnvVarOrUserProperty("checks.disable", "false"));
    }
```
This means, it won't reads the classpathProperties.

Could I ask why some properties could be configured in classpathproperties, but not others? If so, could we have a clear explanation in the documentation? I was thinking all properties will be read and will be merged finally. But apparently no....

Thanks a lot, 
Yingkun

**Comment by bsideup** [comment]
This is intentional.

Some properties are "per project", while other are "per environment". Setting `checks.disable` in `src/test/resources/testcontainers.properties` would disable them for _every_ user of your project, even those who haven't tried to run it yet and may have issues with their setup that would be highlighted by the checks.

Same applies to the reuse mode and a few others.

**Comment by yingkun-bai** [comment]
Thanks a lot for the info. Still, I hope we could have it explained here: https://www.testcontainers.org/features/configuration/
to let people know what should be set where....
