### ISSUE TITLE
Cant run tests

### ISSUE THREAD

**Issue by arnzel** [testcontainers/testcontainers-java#367]
1. import projekt in IntelliJ
2. run "mvn clean install -Pproprietary-deps"
3. Error "Could not resolve dependencies for project org.testcontainers:testcontainers:jar:1.2.2-SNAPSHOT: Failure to find fakejar:fakejar:jar:0 in ..."

**Comment by bsideup** [comment]
Hi @arnzel,

1) You don't have to use Maven to run the tests, you can just run them from IntelliJ as normal JUnit tests
2) Why do you use `proprietary-deps` profile?

**Comment by arnzel** [comment]
Hi, thank you for your answer.

2. -> I read it in the documentation (Topic 'Contributing')

**Comment by kiview** [comment]
I just ran `./mvnw clean install -Pproprietary-deps` in current master and it seems to work. Could you try again using the maven wrapper script?

Or as an alternative try running the tests (or Maven goals) directly from within IntelliJ.

Still we should update the docs in this point I think, since are building the project in Travis with `mvn -B -P !build-extras test`.

**Comment by martinda** [comment]
For command line usage, look in the `.travis.yml` file and follow the instructions in there, specially the commands shown by `install:` and `script:`.
