### ISSUE TITLE
Use .withEnv on DockerComposeContainer won't work as expected

### ISSUE THREAD

**Issue by mbuccini** [testcontainers/testcontainers-java#368]
Hello everyone,

I am trying to use testcontainers in a slightly different way than it's meant to be (i.e., not in unit tests). The reason behind this is that it's quite convenient to have testcontainers because docker-compose is already implemented and the project seems quite stable, so I don't see the point in creating a new wrapper. 

Now, I bumped into an issue which I wonder how can be solved in an easy manner. The following snippet shows how I plan to use test-containers:

```        String containerId = UUID.randomUUID().toString().replace("-", "");
        DockerComposeContainer dockerComposeContainer = new DockerComposeContainer(containerId,
                new File("project/build/resources/main/docker-compose.yml"));

        dockerComposeContainer.withEnv("MY_ENV_VARIABLE", "myValue"));
        dockerComposeContainer.withExposedService(getServiceName(), getPort());
        dockerComposeContainer.starting(null); 
```

However, I noticed that MY_ENV_VARIABLE is only set on the ambassador container (or compose, can't remember). I saw the source code of `org.testcontainers.containers.DockerComposeContainer`, and unfortunately I found out that:  

``` 
    /**
     * Properties that should be passed through to all Compose and ambassador containers (not
     * necessarily to containers that are spawned by Compose itself)
     */
```

I wonder, how do you do it? How would you set environment variables on the containers spawned by compose? Is there a way to force that?

**Comment by kiview** [comment]
I hope we might be able to rewrite the DockerComposeContainer so the amabassador container becomes obsolete (because AFAIK the ambassador container, or at least it's current implementation, was a workaround for the missing docker network support back then). If you are already interested in using the DockerComposeContainer in a more sophisticated use case, maybe you want to look into possible refactorings of the current implementation?
