### ISSUE TITLE
Add support for Strimzy images to KafkaContainer

### ISSUE THREAD

**Issue by jstastny-cz** [testcontainers/testcontainers-java#3932]
Currently, KafkaContainer supports just Confluent images for Kafka, it would be nice to generalize the support to include also other commonly used distributions, e.g. https://strimzi.io/.

**Comment by gunnarmorling** [comment]
+1 to this request. Had logged it before (https://github.com/testcontainers/testcontainers-java/issues/2340), would love to see this being resolved, so we could use Debezium's images, too :)

**Comment by gmunozfe** [comment]
@jstastny-cz @gunnarmorling Strimzi already offers its own implementation for testcontainers:
https://github.com/strimzi/strimzi-kafka-operator/tree/main/test-container

**Comment by eddumelendez** [comment]
@gmunozfe looks like it was removed. But, nowadays, Testcontainers has a [Module Catalog](https://testcontainers.com/modules/) which list modules in the different language implementations, official modules and community modules. In order to list the module, a PR should be submitted to [this repo](https://github.com/testcontainers/community-module-registry). If the module is still there is just a matter to display it in the Testcontainers Module Catalog. Otherwise, we really encourage to host ask the project to provide their own implementation for maintenance purposes, we can still collaborate to guide and build the module following Testcontainers best practices.
