### ISSUE TITLE
Allow customisation of host.testcontainers.internal

### ISSUE THREAD

**Issue by corinapurcarea** [testcontainers/testcontainers-java#3933]
I'm testing a docker setup with 2 Redis sentinels, one Redis master and 2 replicas.

The Redis sentinel container is configured with an environment variable that specifies the Redis master host that the sentinel discovers. The sentinel checks if the Redis host can be resolved(and it is cause i've set it to the env var host.testcontainers.internal) but it also returns the Redis master host to whatever client asks for it.  The issue is that returned host cannot be resolved outside the docker network.

It would be great if host.testcontainers.internal could be customised. In my case, INTERNAL_HOST_HOSTNAME would be set to "localhost", thus making it accessible from within the container as well as outside the container.

```
        PortForwardingContainer.INSTANCE.getNetwork().ifPresent(it -> {
            withExtraHost(INTERNAL_HOST_HOSTNAME, it.getIpAddress());
        });
```

**Comment by bsideup** [comment]
Hi @corinapurcarea,

`host.testcontainers.internal` may not be the right API to use here.

Have you considered doing something similar to how KafkaContainer is working? It delays starting the process before the host/port are available, so that it can pass them to the process and it will return the correct values to the consumer:
https://github.com/testcontainers/testcontainers-java/blob/8965712f239ae3c449cec579264af5e79265f314/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L103

**Comment by corinapurcarea** [comment]
Thanks for the quick answer! 

Unfortunately, the Kafka setup you mentioned doesn't help because the Redis master host must be resolvable from inside docker network as well from outside it.
The application(in my case, the tests) asks sentinel process for the master, but also the sentinel periodically checks if master is available. The application is outside Docker network, the sentinel and master are started with test-containers.

I will leave here 2 solutions for this complicated setup:
- passing the Redis master host as the ip of the host machine.
- using a dns cache manipulator (https://github.com/alibaba/java-dns-cache-manipulator) that will translate host.testcontainers.internal to whatever ip one needs thus making host.testcontainers.internal resolvable from outside as well from inside Docker network.
  ` DnsCacheManipulator.setDnsCache("host.testcontainers.internal", "127.0.0.1");`
