### ISSUE TITLE
Direct HTTPS website access broken

### ISSUE THREAD

**Issue by axelfontaine** [testcontainers/testcontainers-java#429]
How to reproduce: go to [https://testcontainers.org](https://testcontainers.org) (hangs)

What works:
- HTTP [http://testcontainers.org](http://testcontainers.org)
- WWW [https://www.testcontainers.org](https://www.testcontainers.org)

It's very unfortunate as the broken variant is the one linked from a good number of your own GitHub repositories.

**Comment by rnorth** [comment]
Ouch, thanks for flagging. I'll have a look this evening and see what's gone wrong :(

**Comment by rnorth** [comment]
Hmm, I think this might have been a temporary issue - seems to be working for me know (Chrome, Safari, and curl for good measure). I wonder if gitbook was having a blip. Going to close; can reopen if it recurs.

**Comment by axelfontaine** [comment]
FYI it is still not working for me.

**Comment by rnorth** [comment]
OK, this is odd. What browser are you using? Can you get any more fine grained information on where it's hanging, e.g. using `curl -vvv https://www.testcontainers.org`?

**Comment by axelfontaine** [comment]
As I said `https://www.testcontainers.org` is working, but `https://testcontainers.org` (no www) is not.

**Comment by rnorth** [comment]
Sorry, I fixed this a couple of weekends ago and was distracted before updating the ticket. You were quite right, so I apologise for misunderstanding. I think I broke something in the transition to gitbook (which also included moving DNS control from cloudflare to AWS). The solution was to extend the existing Route53+S3 based domain apex redirect with Cloudfront, so that TLS also applied to the apex domain.
