### ISSUE TITLE
How could I use "Indefinite one shot startup strategy" by testcontainer.properties?

### ISSUE THREAD

**Issue by netstart** [testcontainers/testcontainers-java#4299]
I need use "Indefinite one shot startup strategy example"  by testcontainer.properties.
How could I configure using properties?

Reference:
https://www.testcontainers.org/features/startup_and_waits/

**Comment by kiview** [comment]
Hey @netstart,

please consider asking questions in our [discussions](https://github.com/testcontainers/testcontainers-java/discussions) instead of creating an issue. 

Besides, you already referenced the documentation that explains the usage, here the direct link:
https://www.testcontainers.org/features/startup_and_waits/#indefinite-one-shot-startup-strategy-example

Also, it is not clear, what you mean with the reference to `testcontainers,properties`.

**Comment by netstart** [comment]
I'd like configure IndefiniteWaitOneShotStartupCheckStrategy by properties
