### ISSUE TITLE
Upgrade LocalStack module

### ISSUE THREAD

**Issue by HarshCasper** [testcontainers/testcontainers-java#4793]
## Description

Hi 👋 

Testcontainers is currently using an old version of LocalStack and an incompatible configuration setup here: [LocalStackContainer.java](https://github.com/testcontainers/testcontainers-java/blob/master/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java).

This also corresponds with some of the missing features which is further described on this issue: https://github.com/testcontainers/testcontainers-java/issues/3785

It would be ideal to upgrade the LocalStack module for a wider use-case. P.S: LocalStack is no longer under Atlassian Labs, and is a company ([localstack.cloud](https://localstack.cloud)). We would ideally like the inline documentation to be updated as well here 😄

**Comment by rnorth** [comment]
Hi @HarshCasper 
Thanks for getting in touch! 

Firstly, let's update our [docs](https://github.com/testcontainers/testcontainers-java/blob/master/docs/modules/localstack.md) immediately, as I don't think we should be misleading people in this way! Would you have any preference for how to phrase it?

Regarding the old version, this is a slightly more complicated topic. Testcontainers has moved from an approach of ["we'll specify a default image and tag"](https://github.com/testcontainers/testcontainers-java/blob/master/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java#L43) to "users should tell Testcontainers which image and tag to use". The former approach became unsustainable in various modules over time.

Unfortunately we have to maintain backwards compatibility in a couple of dimensions:
* we cannot really change the default tag for any image, because that would potentially change how peoples' tests behave
* we cannot really remove our no-args constructors (e.g. `new LocalstackContainer()`) without causing breaking changes for people

As a result, we have (for all modules) roughly two ways to create a container:
* A _deprecated_ zero-args constructor which has a hardcoded image tag
* A recommended constructor which requires a docker image name. Sometimes (e.g. [here](https://github.com/testcontainers/testcontainers-java/blob/master/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java#L100-L114)) we have conditional logic so that Testcontainers configures the container appropriately according to the image version in use.

I'm afraid I can't see us being able to remove the hardcoded image tags for a while, and the best we can do is to deprecate and hope that users migrate to specifying a more recent image.

I would be curious to learn more about `incompatible configuration setup`. I'd admit that it's been a while since I've looked at our code against Localstack releases. However, some of our team were running some simple use cases with Localstack 0.13.1 just yesterday and not finding any obvious incompatibilities.

We'd be happy to dig into this further, but if you have any specific pointers we'd be more than happy to take them.
