### ISSUE TITLE
Question: is it also possible to use test containers in regular Java environments (so no JUnit/IT tests)?

### ISSUE THREAD

**Issue by rrrrrrrrramba** [testcontainers/testcontainers-java#489]
Hi,

This is rather a question than a bug report. I hope this is the correct place.

I am interested to know if I could also use test containers out of JUnit (`@ClassRule`, ...)? I want to manage docker containers (defined in `docker-compose.yml` configuration files) in a Java application.

All examples on the site are (understandably) in a JUnit context, but is it also possible to work outside such context/maven phase/...? In the end, I would like to package my application as a WAR and deploy it to Tomcat.

Thank you!

**Comment by rrrrrrrrramba** [comment]
Just for information, I tried something like:

```
        final DockerComposeContainer E = new DockerComposeContainer(new File("/home/ramba/docker-test/docker-compose.yml"))
                .withLocalCompose(true)
                .withPull(false);

        System.out.println(E);
        System.out.println(E.getServiceHost("postgresql_1", 5432));
```

But this gives a `NullPointerException` in the second print, while the first prints a reference to a `DockerComposeContainer` object. So I don't really understand why it gives a `NullPointerException`.

**Comment by kiview** [comment]
@rrrrrrrrramba 
Yes, you can use Testcontianers perfectly fine without JUnit (although the dependency is still baked in, we are currently working on modularising the project in order to make JUnit optional, the working title is container-core). We use Testcontainers for all kinds of stuff at my company, as a more convenient Docker library.

As you can see, I'm using the same solution as you've discovered in the Spock extension:
https://github.com/testcontainers/testcontainers-spock/blob/master/src/main/groovy/com/groovycoder/spockdockerextension/TestcontainersMethodInterceptor.groovy#L93

If you need further help, it would be cool if you ask question on [Stackoverflow](https://stackoverflow.com/questions/tagged/testcontainers) or in our Slack channel. You can post a link to the question in this issue if you like.

**Comment by rrrrrrrrramba** [comment]
Thanks!

**Comment by denismakogon** [comment]
Greetings, I'm looking for any convinient tutorial or a doc regarding running testcontainers outside of the tests. More context, I'd like to start an image on a remote host, do the job and kill it, i.e., some sort of container-as-a-service.

**Comment by kiview** [comment]
@denismakogon 
This is outside of the scope of the library and the community.  You can simply [use the regular API](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/).

If Docker is configured to use a remote host, TC will automatically use Docker accordingly.

**Comment by MahatmaFatalError** [comment]
@rrrrrrrrramba maybe this approach might be interesting to you https://bsideup.github.io/posts/local_development_with_testcontainers/
