### ISSUE TITLE
Master testcontainers-java breaks ReadonlyREST

### ISSUE THREAD

**Issue by sscarduzio** [testcontainers/testcontainers-java#493]
Hello guys!
I've been purposely running with:
```
    compile 'com.github.testcontainers.testcontainers-java:testcontainers:master-SNAPSHOT'
```
on my gradle settings for a while. And all went without problems, until recently, when I got this failed build on travis-ci.

https://travis-ci.org/sscarduzio/elasticsearch-readonlyrest-plugin/jobs/302127237

Everything worked again after reverting to the latest stable 1.4.3.

Any ideas?

**Comment by bsideup** [comment]
@sscarduzio 
From the logs:
> Could not build image: The command '/bin/sh -c sed -i "s|debug|info|g" /usr/share/elasticsearch/config/log4j2.properties' returned a non-zero code: 2

Such error might be a flaky test or something caused by https://github.com/testcontainers/testcontainers-java/commit/2ad57da4a4f7b0d3396c4883294aa9c32ef480e7 

May I kindly ask you to try first this one:
`com.github.testcontainers.testcontainers-java:testcontainers:2ad57da4a4f7b0d3396c4883294aa9c32ef480e7` 

And then:
`com.github.testcontainers.testcontainers-java:testcontainers:1c66a143e6513d25b4d60044303b2fabf1c6c0fb`

Thanks for letting us know before it got released! :)

**Comment by sscarduzio** [comment]
Hi  @bsideup,
Just ran this on my laptop. You are right:

2ad57da4a4f7b0d3396c4883294aa9c32ef480e7 <--- test runs
1c66a143e6513d25b4d60044303b2fabf1c6c0fb <--- test fails as above

**Comment by rnorth** [comment]
Thanks for flagging this @sscarduzio - this should be fixed in the latest master. Thanks to your report we'll avoid shipping this bug in a released version 😅 !

**Comment by sscarduzio** [comment]
Thanks @rnorth for fixing this, I can confirm now it works because I reverted the dependency to the master branch of testcontainers-java. 🎉
