### ISSUE TITLE
Some ideas about bypassing the problem that 'databasename' of URIs is omitted

### ISSUE THREAD

**Issue by PisecesPeng** [testcontainers/testcontainers-java#4947]
Hi all,

I tried to create a new demo for Testcontainers, its very useful for me 😁.
there are also some doubts. Relates to [#4121](https://github.com/testcontainers/testcontainers-java/issues/4121).

then write in one way, like [`AbstractIntegrationTest.java`](https://github.com/testcontainers/testcontainers-java/blob/master/examples/spring-boot/src/test/java/com/example/AbstractIntegrationTest.java) and [`Singleton containers demo`](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/)
```java
public abstract class BaseContainerTest {

    static MySQLContainer MY_SQL_CONTAINER = new MySQLContainer(DockerImageName.parse("mysql").withTag("5.7.34"))
            .withDatabaseName("yourdatabase");

    @DynamicPropertySource
    static void mysqlProperties(DynamicPropertyRegistry registry) {
        MY_SQL_CONTAINER.start();
        try {
            StringBuilder newJdbcUrl =
                    new StringBuilder(MY_SQL_CONTAINER.getJdbcUrl()).insert(5, "tc:");
            registry.add("spring.datasource.url", () -> newJdbcUrl);
            registry.add("spring.datasource.username", MY_SQL_CONTAINER::getUsername);
            registry.add("spring.datasource.password", MY_SQL_CONTAINER::getPassword);
        } finally {
            MY_SQL_CONTAINER.stop();
        }
    }

}
```
It works normally, and achieve the effect similar to `jdbc:tc:mysql:5.7.34:///yourdatabase`.
> **ps.** I expect JPA can operate MySQL directly, Instead of creating a connection through the container.

but.. I am very confused.
and I have a few questions about these
> 1. Is it correct to initialize Testcontainer like this?
> 2. How the initialization of the second container happens?

Look forward to your reply!

**Comment by rnorth** [comment]
Hi @PisecesPeng 
Thanks for your kind comment!

This isn't quite how it's intended to be used. You should use _one of_:

(a) putting `tc` into a JDBC URL. This is useful when you have no control over the startup of your code - e.g. you have a service that reads a string JDBC URL from a file, and you can't replace the entire string dynamically.

(b) using an object to construct the container, then calling `getJdbcUrl` and injecting the result into your code/service

Because you're using Spring and DynamicPropertySource, (a) is not what you need, and you should use (b) instead.

You also need to remove `MY_SQL_CONTAINER.stop();` - if you do this, you're telling Testcontainers to delete the container before your service has even started. By chance, because you added `tc` to the URL manually, Testcontainers was creating another container. That won't work well for you :D

Have you tried just:
```java
static MySQLContainer MY_SQL_CONTAINER = new MySQLContainer(DockerImageName.parse("mysql").withTag("5.7.34"))
            .withDatabaseName("yourdatabase");

    @DynamicPropertySource
    static void mysqlProperties(DynamicPropertyRegistry registry) {
        MY_SQL_CONTAINER.start();

        registry.add("spring.datasource.url", MY_SQL_CONTAINER::getJdbcUrl);
        registry.add("spring.datasource.username", MY_SQL_CONTAINER::getUsername);
        registry.add("spring.datasource.password", MY_SQL_CONTAINER::getPassword);
    }
```

**Comment by PisecesPeng** [comment]
@rnorth 
As you said, If I don't remove `MY_SQL_CONTAINER.stop()`, it will cause initializes two containers😅.

What puzzles me is that JPA operates on the second container,
this makes it easier for me to use it in other test classes, instead of using `getJdbcUrl`.
So I did `stopped the first container`.
