### ISSUE TITLE
'EnvironmentAndSystemPropertyClientProviderStrategy' should handle empty DOCKER_HOST

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-java#5026]
Testcontainers fails to start if DOCKER_HOST is set to an empty string.

Reproducer:
```
export DOCKER_HOST=
// run the tests
```

**Comment by roulpriya** [comment]
Hi,

I'm willing to work on this issue.  I tried to reproduce this issue by setting `DOCKER_HOST=` but the test cases were passing. I was running the tests on MacBook pro m1 with macOS=12.6 and docker desktop= v4.12.0 with Docker version 20.10.17, build 100c701

**Comment by kiview** [comment]
Hey @roulpriya, great that you want to look into it.

This issue occurs, if `docker.host` is set in the `~/.testcontainers.properties` file (e.g. to a valid value), but `DOCKER_HOST` is also set and is empty.

It will show such an error:
```
EnvironmentAndSystemPropertyClientProviderStrategy: failed with exception NullPointerException (Cannot invoke "String.hashCode()" because "<local5>" is null)As no valid configuration was found, execution cannot continue.
```

The culprit is like this code right here, since it check only for a key, but not for empty value:
https://github.com/testcontainers/testcontainers-java/blob/de1324ed2800eff4da326d0c23d281399d006bc0/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L232-L234
