### ISSUE TITLE
ScriptUtils cant load postges dump

### ISSUE THREAD

**Issue by ALekseiMokhov** [testcontainers/testcontainers-java#5177]
given:
- Spock with testcontainers;
- Dump from postgres 13.6;
- PostgresqlContainer.withInitScipt(dump.sql);
when:
- container starts;
then:
- It falls with loads of exception: from dropping not existent table till synthax errors, i.e. it can't read "\connect template1".
Is there any workaround?

**Comment by kiview** [comment]
This is very likely related to issues similar to this concrete one:
https://github.com/testcontainers/testcontainers-java/issues/4441

`ScriptUtils` does not support the full extent of all SQL dialects. I would recommend using your regular tooling for managing database schemas (e.g., Flyway or Liquibase).

You can share your dump and we might be able to pinpoint the issues, but I am fairly confident it is because of the reasons above.

**Comment by ALekseiMokhov** [comment]
The funny thing is that we supposed to use TC for proving correctness of liquibase's scipts. Something like custom 
https://github.com/liquibase/liquibase-test-harness
