### ISSUE TITLE
Copy command failed after creating container 'on the fly'

### ISSUE THREAD

**Issue by ALekseiMokhov** [testcontainers/testcontainers-java#5179]
Creating Generic container 
```
    public GenericContainer container = new GenericContainer(
            new ImageFromDockerfile()
            .withFileFromClasspath("Dockerfile", "data/Dockerfile"))

```
with Dockerfile:
```

FROM postgres:13.6-alpine
USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres
COPY data/dump.sql /docker-entrypoint-initdb.d/dump.sql
```

folder structure:
<pre>
 src-
      |_main
                |_resources
                                   |_data
                                             |_Dockerfile
                                             |_dump.sql

</pre>
If I start my container withought TC, it's allright. But with GenericContainer I catch:
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: COPY failed: file not found in build context or excluded by .dockerignore: stat data/dump.sql: file does not exist

**Comment by eddumelendez** [comment]
Hi @ALekseiMokhov 
I guess when you build the container without TC you are located at `src/main/resources` and perform something like `docker build -t test -f data/Dockerfile .` and of course it works because everything is in docker context (taking into account the path of the sql file). However, if you move to `src/main/resources/data` and then run `docker build -t test .` fails because the file `dump.sql` is not in the context.

The same thing happens with TC, as you code displays only the Dockerfile is copied. In this case, `dump.sql` needs to be copied

```java
public GenericContainer container = new GenericContainer(
            new ImageFromDockerfile()
            .withFileFromClasspath("Dockerfile", "data/Dockerfile")
           .withFileFromClasspath("data/dump.sql", "data/dump.sql"))
```

**Comment by ALekseiMokhov** [comment]
Well, thanks a lot for the clarification!
