### ISSUE TITLE
FixedHostPortGenericContainer should be merged to GenericContainer

### ISSUE THREAD

**Issue by Kindrat** [testcontainers/testcontainers-java#555]
Actually, FixedHostPortGenericContainer does not provide any additional logic over GenericContainer - just exposes a protected method to create port bindings. Isn't it more obvious and convenient to change method from protected to public in GenericContainer and remove FixedHostPortGenericContainer class?

**Comment by kiview** [comment]
The general consideration behind this, was AFAIK to discourage the usage of `FixedHostPortGenericContainer` for normal users. An alternative might be, to change the method in `GenericContainer` to public and and an `@Deprecated` annotation, explaining why this is discouraged.

**Comment by Kindrat** [comment]
@kiview saw it, but can't find a reason for such limitation. Test containers is the test library, isn't it? If so, why is it blocking from using common docker cli arg?
`clashes or instability` - that's strange argument b/c it's widely used to start multiple instances of same application binding to different predefined host ports or to rebind common range 0-1024 to some unused ones. Another example could be external service you have no access to - to change its config, so need to start container pointing to exact port you need.

That was not obvious that you need to use an additional class, the only purpose of which is to expose protected method...

**Comment by kiview** [comment]
The Javadoc says this:
```
/**
 * Variant of {@link GenericContainer} that allows a fixed port on the docker host to be mapped to a container port.
 *
 * <p><strong>Normally this should not be required, and Docker should be allowed to choose a free host port instead</strong>.
 * However, when a fixed host port is absolutely required for some reason, this class can be used to set it.</p>
 *
 * <p>Callers are responsible for ensuring that this fixed port is actually available; failure will occur if it is
 * not available - which could manifest as flaky or unstable tests.</p>
 */
```
which is true I'd say, especially regarding CI environments running multiple tests and instances of testcontainers tests in paralell. However, as I said, I would not be against adding it as a public API. @rnorth or @bsideup might need to clear things up regarding this design decision.

**Comment by rnorth** [comment]
Yes, the reason is basically as @kiview previously indicated.

In most cases, for many reasons, using a randomised host port is the right thing to do. I want the path of least resistance to lead to doing the right thing, and this means that other options have to be comparatively difficult.

If we make this a public API on `GenericContainer` then people will accidentally pick the fixed host port option when there's no strong reason to do that. For example, picking the wrong method from autocomplete, not downloading/reading the Javadocs, just not thinking about the implications of having a fixed host port and defaulting to what they've always done, etc. 

And then later on, they'll be caught out with environment differences, parallelisation issues, etc, which are exactly the kind of things that Testcontainers is supposed to protect against.

I'm aware that there are still a few legitimate cases for having fixed ports, sadly, so we have exposed this via the `FixedHostPortGenericContainer` class. However, it is not something we want the average developer to be able to accidentally pick. We want people to be fully aware that, if they used a fixed port, Testcontainers will not be able to do its job properly.

I'm sorry, but this is not a decision that I want to change, so I'm going to close this ticket.

Presumably, though, this arose because you've had the need to use fixed host ports and found it awkward. I'm curious which product you're encountering this with, and wonder if there is another way to achieve what you're looking to do. If you'd like more eyes on the problem, perhaps this is something we could look at on Slack together.

**Comment by Kindrat** [comment]
I still disagree with comparing it to wrong autocompletion b/c someone won't read docs... To my understanding - at first, a library should provide convenient documented API b/c there will be always someone who will use it in the wrong way with any of remaining public methods. Sad, but will need to override `GenericContainer` in my code to use that method...
