### ISSUE TITLE
[Feature]: Enable Helm Charts usage

### ISSUE THREAD

**Issue by lynch19** [testcontainers/testcontainers-java#5607]
### Module

New Module

### Problem

I want to use TestContainers in a CI environment, that run on K8s. I'm using Jenkins, and I have no Docker runtime abilities - hence Testcontainers is unusable.

### Solution

I'd like to have a module in testcontainers that will be similar to the `testcontainers-docker-compose` module, but for Helm Charts. This will make Testcontainers unusable to me, to an awesome library that will help me perform tests. Basic Helm charts support will let me create anything I will need - MongoDb, Kafka, anything, during my tests!

In my opinion, this feature can level up Testcontainers for many people.

### Benefit

This will open the door for making Testcontainers an ultimate DevOps library, instead of a specific technology vendor-locked (for Docker) library.

### Alternatives

Resolve this super important issue. https://github.com/testcontainers/testcontainers-java/issues/1135

### Would you like to help contributing this feature?

Yes

**Comment by kiview** [comment]
Thanks for raising the feature request @lynch19. However, Testcontainers by design requires a container runtime with a Docker compatible API and is based on multiple assumptions for the container runtime to share specific characteristics with Docker. We don't see how your feature request fits into the current vision of Testcontainers.

> I'm using Jenkins, and I have no Docker runtime abilities - hence Testcontainers is unusable.

Please note that Testcontainers does not require a Docker-compatible runtime to be present on the same host that executes the test. Testcontaners supports configuring a remote host and many users in the community have such setups in specific CI environments.

As a side note, you can use this Testcontainers module to test helm charts itself (running Kubernetes in Docker):
https://github.com/dajudge/kindcontainer

**Comment by lynch19** [comment]
@kiview A remote host is indeed a good solution and I will check on this (I guess you mean that I should run Docker on some VM and reference it from the k8s cluster in which the CI enviornment is set on, right?).

But in general, don't you think that this is where the library should be heading? Using Helm instead of Docker will enable usage of Testcontainers in a pure K8s enviornment. Wouldn't it be awesome and super confortable for k8s users? And as you probably know, most of us are pure k8s users (no easy access for VMs and stuff).

**Comment by kiview** [comment]
> I guess you mean that I should run Docker on some VM and reference it from the k8s cluster in which the CI enviornment is set on, right?

That is indeed one possible way to set this up.

> Using Helm instead of Docker will enable usage of Testcontainers in a pure K8s environment.

This sounds like a weird argument given the reasons I outlined above, with Testcontainers interacting with a container runtime (not an orchestrator runtime) for a specific kind of test (which some might define as integration tests, but not large-scale system tests). You are of course free to explore other alternatives if you feel as if Testcontainers does not cater to your specific use cases.

**Comment by DRoppelt** [comment]
> I want to use TestContainers in a CI environment, that run on K8s. I'm using Jenkins, and I have no Docker runtime abilities

I would like to point out that this not not quite as black&white. You can get docker to run in k8s by using a dind-rootless (dind=docker-in-docker) image as the container hosting the necessary daemon for testcontainers`.

https://github.com/testcontainers/testcontainers-java/issues/1135#issuecomment-904526644

If you are using the kubernetes plugin in Jenkins, you can setup following podspec:

- 2 containers, one is named jnlp (optional, as jenkins brings its own jnlp container if nothing is set). The other "dind-rootless"
  - the client, the one using the daemon to i.e. start docker containers, is the jnlp container
  - in my env we have custom jnlp containers anyways, so YMMV
- shared emptyDir on `/certs`, which allows the client to access the certs of the daemon. The daemon creates them on startup
- client: env `DOCKER_HOST=tcp://localhost:2376` to change the port due to tls
- client: env `DOCKER_TLS_VERIFY=1` 
- client: `DOCKER_CERT_PATH=/certs/client` so that it knows where to fetch the certs
- set a flag for elevated priviledges (not sure if it is on pod or container level) 

Thats how I got it to run in my Jenkins environment. The started pod has 2 containers, the jnlp is where the CI happens (e.g. it is a jdk17 with some added tools) the second container hosts the docker daemon required for testcontainers. The 2 containers talk with each other via localhost.
I can do `docker build ...`, `docker run ...` and use testcontainers via maven just like a regular local build.
The setup might be condensed down to a simpler config, but a rootless container was necessary in my env. It has some restrictions (https://docs.docker.com/engine/security/rootless/), which, tbh, I do not understand but seem to be irrelevant for CI.

**Comment by DRoppelt** [comment]
@lynch19 I am not sure if you got a notification from my previous comment, but since this seems to be an urgent issue for you, I am pinging you this way. With https://github.com/testcontainers/testcontainers-java/issues/5607#issuecomment-1196587457 you can get a pod to a dockerdaemon and therefore get testcontainers to work. Essentially you move a docker daemon into the pod instead of reying on k8s to have a dockerdaemon itself (which was the case pre k8s 1.19? or so)
