### ISSUE TITLE
Use the default docker-machine

### ISSUE THREAD

**Issue by buckett** [testcontainers/testcontainers-java#63]
docker-machine is now assuming a default machine of "default" if you don't specify anything else. I think it would make sense for testcontainer to follow this lead.

https://github.com/docker/machine/pull/2843

**Comment by rnorth** [comment]
Ah, thanks for raising this - I wasn't aware of this change in docker-machine! I'd definitely be happy to do this.

I believe that the behaviour we should aim for is:

- If the DOCKER_MACHINE_NAME environment variable is set, use that
- Otherwise use 'default'

As Testcontainers execs the docker-machine binary to find out the machine's IP address I'd imagine we need to pass through the resolved name - unless the environment variables are inherited, which I'd need to check.

Thanks
Rich

**Comment by rnorth** [comment]
Thinking about this I'll adopt a slightly different approach to my comment above:

- If the DOCKER_MACHINE_NAME environment variable is set, use that
- Otherwise, if 'default' exists, use that
- Otherwise fall back to using the first machine found in the docker-machine list

This should be backwards compatible with the previous way - and seems most likely to do the right thing by the user.

**Comment by rnorth** [comment]
I've just released v1.0.1 with this change. Thank you for the suggestion!
Richard
