### ISSUE TITLE
Hangs after checking disk space

### ISSUE THREAD

**Issue by bjhartin** [testcontainers/testcontainers-java#655]
When starting a container, I see hangs of up to 130 seconds right after the 2 GB  disk space check.  It's highly variable and I've seen it as fast as 20 seconds.

The [full log is here](https://gist.github.com/bjhartin/753865476a57c20962fee5c51820540a).

There is an error in the log at that point which does not show up elsewhere:

`Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer`

There's an error early in the log I'm not sure if it's related:

`jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe`

OS: OSX Sierra
JDK: 1.8.0_31
SBT: 1.1.1
Library versions: org.testcontainers:testcontainers:1.6.0; com.dimafeng:testcontainers-scala_2.12:0.15.0

**Comment by bsideup** [comment]
Hi @bjhartin,

I see that you're using Docker Machine. Is it intentionally? You might be affected by #527
We highly recommend Docker for Mac since it is the stablest solution for Mac and actively tested.

Please also update Testcontainers' version to 1.7.1 to make sure that you use the latest changes

**Comment by bjhartin** [comment]
Switching from Docker Machine to Docker For Mac dropped my test time to 7 seconds.  Thanks @bsideup!
