### ISSUE TITLE
[Bug]: image removal in multi-stage dockerfile after container stop

### ISSUE THREAD

**Issue by minakh1993** [testcontainers/testcontainers-java#6948]
### Module

Core

### Testcontainers version

1.17.5

### Using the latest Testcontainers version?

No

### Host OS

Windows

### Host Arch

-

### Docker version

```shell
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

defined image as below but after test execution, created image is not removed.
`new CmApplicationContainer(new ImageFromDockerfile().withDockerfile(Path.of(dockerfile)))`

an extra image is created that has no tag or name:
```
REPOSITORY TAG IMAGE ID CREATED SIZE
none none 888ca210c487 3 minutes ago 605MB
```

the main image that is created from imageFromDockerfile is removed correctly but this unknown image still exist after tests.
as i inspect the problem deeply this problem happen in multi-stage docker file.  when i changed the dockerfile to simple type the none image removed correctly after tests.

**Comment by StefanHufschmidt** [comment]
I can confirm that the `<none>` image will stay if you build any other target than the first one of a Docker multistage build file. Interestingly Testcontainers tests have already one test case to cover the first target of a multistage Dockerfile (https://github.com/testcontainers/testcontainers-java/blob/66bcd391df31c4afdac32ff325974fe0f62968c8/core/src/test/java/org/testcontainers/containers/MultiStageBuildTest.java#L13). This can be used for reproducing the issue by removing the `.withTarget` option.

From my point of view, this might be an issue of the docker-java library since Testcontainers just uses the BuildImageCmd from this library for building the image. Images created by Testcontainers get some labels to let Ryuk delete it after everything is done. Those labels will not be applied to the `<none>` image containing the other layer than the final layer of our multistage build.

**Comment by eddumelendez** [comment]
This was reported also in Testcontainers for .NET. [This](https://github.com/testcontainers/testcontainers-dotnet/issues/602#issuecomment-1270822927) is the answer and the link to the explanation in moby.
