### ISSUE TITLE
Should use Oracle Maven repository to obtain Oracle JDBC driver

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#73]
Now that the Oracle JDBC driver is available in a public repository, the `oracle-xe` module can be part of the CI build and there is no need for the proprietary-deps profile.

**Comment by kaiwinter** [comment]
Yes that would be great, but the oracle repository requires you to authorize yourself with your oracle account. It's not possible to have a private maven config where you can securely store this credentials on Circle CI I think. Do you have an idea on how to solve this?

Reference: [Get Oracle JDBC drivers and UCP from Oracle Maven Repository ](https://blogs.oracle.com/dev2dev/entry/how_to_get_oracle_jdbc)

**Comment by rnorth** [comment]
Ah crap, I'd seen the other [announcement](https://blogs.oracle.com/dev2dev/entry/oracle_maven_repository_instructions_for) but not groked the detail about needing to still use credentials. CircleCI's environment variables _can_ technically be used to get credentials into the build, but to be secure you have to disable builds of PRs (in case they modify the build to steal the credentials). This isn't something I'd want to do.

Oh well, maybe something to come back to one day, but seems pretty improbable :(

**Comment by gdubya** [comment]
The time has come.... :) https://medium.com/@kuassimensah/oracle-jdbc-drivers-on-maven-central-64fcf724d8b

**Comment by rnorth** [comment]
Thanks for re-opening 😀 

Contributions would be welcomed!

**Comment by kaiwinter** [comment]
This is undoubtedly great news. **BUT** I'm afraid I have to crash this party again somehow: It turned out that Oracle doesn't tolerate public Oracle docker images and sends DMCA Takedown Notices. 

I was using wnameless/docker-oracle-xe-11g which was removed from Docker Hub because of this in the past. This issue sums it up: https://github.com/jhipster/generator-jhipster/issues/9370.

I'm going to contribute a small change to the oracle-xe module to use an official JDBC driver but `OracleJDBCDriverTest.testOracleWithNoSpecifiedVersion` which is currenty annotated to be ignored cannot be un-ignored as there is no safe docker image.

**Comment by bsideup** [comment]
fixed in https://github.com/testcontainers/testcontainers-java/pull/1899
