### ISSUE TITLE
[Feature]: fake-gcs-server

### ISSUE THREAD

**Issue by ivanyu** [testcontainers/testcontainers-java#7495]
### Module

New Module

### Problem

Hi!

The same way as Localstack S3 is useful for testing code working with AWS S3, [fake-gcs-server](https://github.com/fsouza/fake-gcs-server) is useful for Google Cloud Storage. It would be convenient to have it supported by Testcontainers without extra effort.

### Solution

I have a [Testcontainer wrapper](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/blob/main/storage/gcs/src/integration-test/java/io/aiven/kafka/tieredstorage/storage/gcs/FakeGcsServerContainer.java) around `fake-gcs-server`. Would you like it to be contributed to this repo?

### Benefit

Users can use `fake-gcs-server` without writing own wrappers.

### Alternatives

- A side dependency (I'm going to do this is this proposal is rejected).
- Not do this and let users create their own wrappers.

To the best of my knowledge, `fake-gcs-server` is the best Docker imitation of GCS.

### Would you like to help contributing this feature?

Yes

**Comment by eddumelendez** [comment]
Hi @ivanyu, sorry for the delay. I see there is a [module](https://github.com/Aiven-Open/testcontainers-fake-gcs-server) available now. Did you know there is a [Module Catalog](https://testcontainers.com/modules/)? For now, we encourage module authors to host the modules. Would you mind sending a PR to [this repository](https://github.com/testcontainers/community-module-registry) in order to make it available in the Module Catalog, please?

**Comment by ivanyu** [comment]
Thanks @eddumelendez, sounds good, will do this!

**Comment by ivanyu** [comment]
Done: https://github.com/testcontainers/community-module-registry/pull/20
