### ISSUE TITLE
getMappedPort does not get updated port number for restarted containers

### ISSUE THREAD

**Issue by aahmed-se** [testcontainers/testcontainers-java#761]
Restarted containers map exposed randomly so a object instance getMappedPort method will return an in valid entry as if caches the original port mapping during container initialization.

Need to provide a container restart resilient api.

**Comment by kiview** [comment]
How did you restart the container? 
Currently, stopping removes the container:
https://github.com/testcontainers/testcontainers-java/blob/007c3b9df12145f5175a7dd17c476a01e6f1f5b8/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L348

So you actually want a `restart()` feature?

**Comment by aahmed-se** [comment]
we extends generic container in our internal tools to provide to primitive chaos testing

like so 
```
    public void restartContainer() {
        this.dockerClient.restartContainerCmd(this.getContainerId()).exec();
    }
```
The issue here me need to support reconfiguration of the mapped ports to support restart type operations with the current api

**Comment by jellenelis** [comment]
I just hit this exact issue. Has there been any progress on this one? 
My use case is to test a container gracefully being stopped, after which it should be started again to test other functionality (in a system test).
`GenericContainer#stop()` kills the container, so I used the docker client to stop the container. Restarting afterwards also has to be done using the docker client, because `GenericContainer` does nothing on `start()` if the containerId is already set.
Getting mapped ports after a restart, return the previously mapped ports.

**Comment by bsideup** [comment]
The easiest workaround would be to use:
```java
            @Override
            public InspectContainerResponse getContainerInfo() {
                return getCurrentContainerInfo();
            }
```

We do not support restarting the containers as it causes various side effects (like new the new set of ports as you observe) and instead I would recommend restarting the process inside the container instead. That said, if you _really_ need to do this - just force `getContainerInfo` to return the current one (it can/should also be cached after the restart)

**Comment by bsideup** [comment]
I am going to close this issue as there is a workaround.
