### ISSUE TITLE
[Enhancement]: TESTCONTAINERS_RYUK_DISABLED for property file

### ISSUE THREAD

**Issue by Osmyslitelny** [testcontainers/testcontainers-java#7725]
### Module

Core

### Proposal

Add opportunity to disable ryuk from testcontainers.properties file or env variable.
We have the same for a lot of other settings.
For example: file property `ryuk.disabled=true` (`testcontainers.ryuk.disabled=true`) or env variable `TESTCONTAINERS_RYUK_DISABLED=true`.

**Comment by eddumelendez** [comment]
Have you checked the [docs](https://java.testcontainers.org/features/configuration/#disabling-ryuk)? Disabling ryuk can be done via env vars already but it is not encouraged to do so because Ryuk is the one in charge of cleaning the resouces (images, containers, volumes, networks) in your container runtime.
