### ISSUE TITLE
[Enhancement]: Introduce missing AWS services in Service implementation of EnabledService

### ISSUE THREAD

**Issue by MatejNedic** [testcontainers/testcontainers-java#7762]
### Module

Localstack

### Proposal

Currently only part of Localstack Services is available in EnabledService implementation. Extend the list with missing services or create a new method that simplifies a use.

I am willing to introduce a new enums and make PR if this is something worth having.

**Comment by eddumelendez** [comment]
Hi Matej, thanks for raising the issue. However, starting in LocalStack 0.13 services env var is optional because of [Lazy-loading services](https://github.com/localstack/localstack/releases/tag/v0.13.0). I think the main reason about introducing the enums was the port assigned to every AWS service in LocalStack. But, that's not the case anymore, everything is available via port 4566. Nowadays, `LocalStackContainer#getEndpoint()` should be used instead. Due to `SERVICES` in just an env var which is not going to be used to get the port then declaring `withEnv("SERVICES", "ec2,kinesis")`

**Comment by MatejNedic** [comment]
Hey Eddu, perfect thanks, will lift than version of testcontainers on spring cloud AWS since getEndpoint is not implemented in 1.18.0
