### ISSUE TITLE
 Unable to pull from private Google Container Registry (gcr)

### ISSUE THREAD

**Issue by mrtnrdl** [testcontainers/testcontainers-java#812]
I'm trying to pull from a private registry in the google cloud with testcontainers. Up until now, I've used short-lived credentials generated via gcloud docker -a and it worked flawlessly.
For docker versions > 18.03, this has been deprecated.

I'm now trying to move to use gcloud as a credential helper for docker (according to the documentation here).
This does not work, because when I do not yet have the image locally, it fails to pull it from the registry with the following exception:

org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=eu.gcr.io/projectName/gcloud-emulators-datastore:latest)

When i manually docker pull eu.gcr.io/projectName/gcloud-emulators-datastore:latest it works without the need to do any more authentication etc, because I'm already authenticated via gcloud.

(I'm using testcontainers-scala and raised the issue [there](https://github.com/testcontainers/testcontainers-scala/issues/27#issuecomment-409414540) - But it does not appear it has anything to do with this code.)

**Comment by rnorth** [comment]
Hmm, we released support for docker credential helpers just recently (1.8.1). I’m afraid I’m AFK right now so can’t check whether the scala libs currently use this version of the Java library, but when they do this should just work automatically!

We use this with ECR rather than gcloud registry but both should operate identically (if not, it’s a problem!). 

Just FYI the credential helper support is for Linux and Mac only right now, as that’s all we had time to test so far.

**Comment by mrtnrdl** [comment]
Hi @rnorth. Thanks for the quick reply! 
Testcontainers-scala are currently using 1.8.0 - I'll try upgrading and will see if it works. Thanks a lot!
