### ISSUE TITLE
[Enhancement]: Mockserver still uses deprecated Docker iumage

### ISSUE THREAD

**Issue by ClumsyPenguin** [testcontainers/testcontainers-java#9072]
### Module

MockServer

### Proposal

The default image of Mockserver still references the deprecated images `https://hub.docker.com/r/jamesdbloom/mockserver`

`private static final DockerImageName DEFAULT_IMAGE_NAME = DockerImageName.parse("jamesdbloom/mockserver");
`

It should use this reference `https://hub.docker.com/r/mockserver/mockserver`

**Comment by eddumelendez** [comment]
Hi, `mockserver/mockserver` image is used already in `MockServerContainer`, see [implementation](https://github.com/testcontainers/testcontainers-java/blob/main/modules/mockserver/src/main/java/org/testcontainers/containers/MockServerContainer.java#L37).
[Docs](https://java.testcontainers.org/modules/mockserver/) also mention it.

`jamesdbloom/mockserver` can not be removed because can break users still using that image.
