### ISSUE TITLE
Wait only for some of ports

### ISSUE THREAD

**Issue by bojanv55** [testcontainers/testcontainers-java#933]
When using testcontainers this way:
```
new GenericContainer("shopify/toxiproxy")
	.withExposedPorts(8474, 3305);
```
it is waiting for port 3305 to become available which will happen only after other part of my code connects to 8474 and executes command.

Is it possible to instruct GenericContainer to wait only for port 8474 and not 3305, but to expose both ports?

**Comment by bsideup** [comment]
Hi @bojanv55 

I really suggest you to override `containerIsStarting` and do the commands in it, it gets executed before the liveness checks

**Comment by bojanv55** [comment]
@bsideup not sure if you understood me correctly. The problem is not that I cannot execute commands, but the workflow is that it should be executed after the container is completely up and running. This just seems like missing feature in testcontainers.

Anyway, for now, I just did quick workaround using:

`.waitingFor(Wait.forLogMessage(".*8474.*\\n",1));`

**Comment by rnorth** [comment]
To be honest, I think your workaround is the right thing to do, @bojanv55.

The default, unconfigured, wait behaviour is to wait for all exposed ports to be listening. Most of the time, that's the right thing to do, because it usually means that the process inside the container is ready for action. This is intended to be good enough to serve as a no-config default.

In some cases, like some DBs and Selenium, the ports listening is not enough, so we have to wait for a line in the logs. 

I've never come across a situation like the problem you have with using toxiproxy, so it's a new scenario. But I think the best thing to do is exactly what you've done - wait for a message in the logs.
